### ISSUE TITLE
RectangularButtonView options stroke is not being acted upon

### ISSUE THREAD

**Issue by bereaphysics** [phetsims/sun#157]
The RectangularButtonView checks if options.stroke is null (or non null) but never passes the option value of stroke to enabledStroke and disabledStroke. Assigning to #JB or #SR, the authors of rectangularButtonView

**Comment by jbphet** [comment]
I just took a look at this, and I think the stroke _is_ being acted upon, it's just not immediately obvious how because the code is a bit complicated.  The options.stroke value is used in the creation of the overlayForHorizGradient, which ends up creating the stroke and putting above everything else in the z-order.  

The sun demo tests many of the stroke options, and they all work as far as I can tell.  @bereaphysics - is there a specific case you can describe that isn't working?

**Comment by bereaphysics** [comment]
in ButtonDemoView.js you can try to change the color of stroke and it has no effect on the color of the stroke. I made the lineWidth very large so that the effect would be apparent.
```
    var fireOnDownCount = 0;
    var fireOnDownButton = new RectangularPushButton( {
      content: new Text( 'Fire on Down Button', { font: BUTTON_FONT } ),
      listener: function() { message( 'Fire on down button pressed ' + ( ++fireOnDownCount ) + 'x' ); },
      baseColor: new Color( 255, 255, 61 ),
      fireOnDown: true,
      stroke: 'green',
      lineWidth: 10
    } );
````

**Comment by bereaphysics** [comment]
![image](https://cloud.githubusercontent.com/assets/7633344/6340307/33ae1578-bb7b-11e4-9e2f-3cab47901a82.png)

That what it looks like

**Comment by jbphet** [comment]
Got it.  I found the issue - stroke values specified in the options were not being used, and a darkened version of the base color was used instead.  Will assign to @bereaphysics to verify.

**Comment by bereaphysics** [comment]
I tested the three scenarios: setting a color stroke, a value set to null, or just undefined. Everything works as expected.
