### ISSUE TITLE
tandem should not be passed to supertype

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#192]
In general, if a type calls `tandem.addInstance`, then the tandem should not be passed to the supertype, as this can lead to multiple calls to addInstance. There many examples in sun (CheckBox, ComboBox, HSlider, OnOffSwitch, RadioButton, RoundPushButton, ...) where a subtype calls tandem.addInstance, and then proceeds to pass the tandem to its supertype.

**Comment by samreid** [comment]
Well, this will need further discussion.  It may be essential in some cases to pass the tandem to the parent so that children (from composition) can register themselves.  What you cannot do at the moment is register the same instance twice, but perhaps we will find a way around this issue or make it so that each level in a type hierarchy can be registered.

**Comment by pixelzoom** [comment]
7/14/15 dev meeting consensus: If you pass a tandem through options, don't pass it to supertype unless you document why you're doing so.

**Comment by pixelzoom** [comment]
This is still an issue, and has come up again in https://github.com/phetsims/beers-law-lab/issues/131. Let's resolve this.

**Comment by samreid** [comment]
I proposed a band-aid in https://github.com/phetsims/beers-law-lab/issues/133

> Perhaps we need a way to pass the tandem to the parent, but with a flag to "only register children, not the node itself". This seems complicated but it would solve the problem at hand. Tagging @pixelzoom to get his thoughts on the matter.

@pixelzoom responded:

> A flag to "only register children, not the node itself" sounds like a bandaid. And this problem will occur again, so I'd like to find a cleaner solution. Since this is due to an ordering dependency caused by TDraggableNode, I think we should address this after phetsims/together#254 (various issues related to TDraggableNode)

**Comment by samreid** [comment]
One way to implement the band-aid (if we decide to continue with it) would be to create a new Tandem method, something like `tandem.createSupertypeTandem()`.  It would be used like this:

```js
// for the sake of discussion, pretend that we are dealing with some Button subtype
function ButtonSubType(args){
  Button.call(this,{tandem:tandem.createSupertypeTandem()}
  // ...
  tandem.addInstance(this);
}
```

createSupertypeTandem could transform addInstance into a no-op and otherwise behave like a normal Tandem (thus allowing sub-tandems to be created, registered, etc.)

Even though this approach was proposed as a band-aid, the API proposed above doesn't feel entirely hack-ish.  It is certainly better than what we have now, which is nothing.

@pixelzoom can you take a look at your convenience?

**Comment by pixelzoom** [comment]
In the situations mentioned in https://github.com/phetsims/sun/issues/192#issue-94811675, why do the subtypes need to call addInstance? Why shouldn't this be the responsibility of the supertype?  I suspect that rather than needing a workaround like `tandem.createSupertypeTandem`, we need to simply put the call to `addInstance` where it belongs.

**Comment by samreid** [comment]
When an instance is registered with tandem, it may be customized by any customization code.  For instance, let's say a client wants to customize the text on a TextButton (which, for the purposes of this discussion) extends Button.  Here is the sequence of actions *if Button calls addInstance*:

1. TextButton constructor invoked
2. TextButton calls Button.call(this,...)
3. Button calls tandem.addInstance
4. Together receives a callback that the button has been registered
5. Together tries to customize the text on the button.  This causes a runtime error since the button doesn't have any text yet (since the TextButton constructor hasn't finished being called).

Synchronous customization is important since changing the size of components could change the layout.

Thus I proposed the strategy of TextButton passing a superTandem to Button so that TextButton.   Both will call `addInstance` but it will be no-op in Button since TextButton knows it is subclassing a tandemized component.  Subsequently, if I subclass TextButton, adding some other features (like a highlight), then HighlightTextButton would pass a superTandem to TextButton (hence giving it a no-op `addInstance`), then it would call `addInstance` itself.  The main point is not to register "incomplete" objects with tandem.

**Comment by pixelzoom** [comment]
So if I'm passing the tandem to a supertype constructor, when would I pass anything other than `tandem.createSupertypeTandem()` ?  Wouldn't this pattern would need to be used in all cases involving inheritance.

Another solution would be to call the supertype constructor last (which is the pattern I've been using lately when extending Node), but I realize that creates an order dependency and isn't practical.  Just thought I'd mention is so we can rule it out.

**Comment by samreid** [comment]
Yes, if we adopt this paradigm, we would probably adopt the convention of always calling `tandem.createSupertypeTandem()` when dealing with tandems in subclasses.

Calling the supertype constructor last makes it impossible to call supertype methods during the subtype constructor, so it seems impractical in the general case.

**Comment by pixelzoom** [comment]
Still not wild about this pattern, but I don't have an alternative to suggest. Should we ask other developers for ideas?

**Comment by samreid** [comment]
> Still not wild about this pattern, but I don't have an alternative to suggest. 

You summarized my thoughts exactly, I'll put this on agenda for an upcoming developer meeting. It would also be great if @jonathanolson @jessegreenberg and @jbphet could take a look in advance.  If we could get this sorted out before the next meeting, so much the better!

**Comment by samreid** [comment]
@pixelzoom pointed out that instances in the simulation may be constructed dynamically (like a scene being created dynamically), so applying customizations as a batch after the sim started up may be difficult.

**Comment by jbphet** [comment]
This was discussed in the 1/12/2016 dev meeting, and after going around for a bit, decided that we didn't have better ideas than ```tandem.createSupertypeTandem```.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/scenery-phet/issues/171

**Comment by pixelzoom** [comment]
Should we consolidate this issue and phetsims/scenery-phet#171 in a new issue in the proper repository? (which I believe would be tandem).

**Comment by samreid** [comment]
> Should we consolidate this issue and phetsims/scenery-phet#171 in a new issue in the proper repository? 

Yes.  I created https://github.com/phetsims/tandem/issues/7

**Comment by pixelzoom** [comment]
@samreid Can we close this issue?

**Comment by samreid** [comment]
Yes, closing.
