### ISSUE TITLE
Standardize API for touch area expansion

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#204]
During Nov 10 developer meeting, @pixelzoom said:

> Should we look through the naming of touchExpansion, touchAreaExpansion, touchAreaDilation, etc and make them consistent?

We agreed this would be good to look at eventually, though not high priority.  This applies to all common repos (including but not limited to sun).

**Comment by pixelzoom** [comment]
This issue was create in sun, but it also applies to scenery-phet and other repositories that use the scenery pointer area features (`mouseArea` and `touchArea`).

There is currently no standardization of this API, the option names are all over the place. A quick survey shows the following examples (not complete) in common code:

```
// scenery-phet
ArrowButton: {number} xTouchExpansion, yTouchExpansion
EyeDropperNode: {number} buttonTouchAreaDilation
LaserPointerNode: {number} buttonTouchExpansion
LeftRightSpinner: {number} touchExpansion
NextPreviousNavigationNode: {function} touchAreaExtension
NumberSpinner: {number} touchAreaExpandX, touchAreaExpandY, mouseAreaExpandX, mouseAreaExpandY
WavelengthSlider: {number} thumbTouchAreaExpandX, thumbTouchAreaExpandY

// sun
AccordionBox: {number} buttonTouchAreaDilatedX, buttonTouchAreaDilatedY, buttonMouseAreaDilatedX, buttonMouseAreaDilatedX
RadioButtonGroup: {number} xTouchExpansion, yTouchExpansion, xMouseExpansion, yMouseExpansion
RectangularButtonView: {number} xTouchExpansion, yTouchExpansion
RoundButtonView: {number} touchExpansion
VerticalAquaRadioButtonGroup: {number} touchXPadding, mouseXPadding
```

I need to add this API to sun.Carousel (see https://github.com/phetsims/sun/issues/213), so rather than create more lack of standardization, perhaps we should decide on a standard sooner rather than later.

**Comment by pixelzoom** [comment]
Also worth noting is the the tendency in common code to support `touchArea`, but not `mouseArea`.  The cost to implement both at the same time is significantly lower than the cost to add `mouseArea` later.  So perhaps we should (as a general policy) implement support for both `touchArea` and `mouseArea` at the same time.

**Comment by samreid** [comment]
@pixelzoom will propose a standard

**Comment by pixelzoom** [comment]
Proposal:

For rectangular components (eg, RectangularPushButton):

`touchAreaXDilation`
`touchAreaYDilation`
`mouseAreaXDilation`
`mouseAreaYDilation`

For round components (eg, RoundPushButton):

`touchAreaDilation`
`mouseAreaDilation`

For rectangular subcomponents (eg 'button' in AccordionBox):

`buttonTouchAreaXDilation`
`buttonTouchAreaYDilation`
`buttonMouseAreaXDilation`
`buttonMouseAreaYDilation`

For pointer areas related to round subcomponents (eg 'button' in LaserPointerNode):

`buttonTouchAreaDilation`
`buttonMouseAreaDilation`

@samreid @jbphet @jonathanolson @jessegreenberg feedback please.

**Comment by samreid** [comment]
https://github.com/phetsims/sun/issues/204#issuecomment-170137876 sounds good to me

**Comment by jonathanolson** [comment]
Looks great to me.

**Comment by jessegreenberg** [comment]
This seems great to me.

**Comment by pixelzoom** [comment]
Since it has a +1 from everyone except @jbphet, I'm going to proceed with the proposal in https://github.com/phetsims/sun/issues/204#issuecomment-170137876.

**Comment by pixelzoom** [comment]
I implemented the proposal in https://github.com/phetsims/sun/issues/204#issuecomment-170137876 for common code, and tried to use the "dilation" terminology consistently in sims by inspecting searches for things like "expand", "expansion", "padding", "touchArea =", "mouseArea =". 

Since @jbphet didn't weigh in on this, assigning him to take a peek so that he's aware that this has been done.

**Comment by jbphet** [comment]
Peek taken, looks good, closing.
