### ISSUE TITLE
several mentions of "together" in comments and annotations

### ISSUE THREAD

**Issue by jbphet** [phetsims/sun#208]
in the course of working on adding visibility annotations (see #195), I noticed that there are a number of comments and annotations that mention the ```together``` feature/repository.  That repository is private, and the ```sun``` repo is intended to be potentially used without ```together``` and without much of the other PhET infrastructure.  Should these comments be modified to reference ```tandem``` instead?  Or say ```phet-io```?  Or be removed entirely?  I suspect that these references would be confusing to any potential non-PhET users of this library.

**Comment by samreid** [comment]
I think `@public (together)` is the most accurate modifier for such instances, because it is the together wrapper code that would want to access these attributes.  Alternatively, the attributes could register themselves with tandem--it is unclear to me when we should favor one approach over the other or if we could get away with only one approach.

Whether we have docs referring to together, or methods referring to tandem, I think it could be confusing to outside parties--we could document in the PhET Development Overview what this is, but I presume that most developers would just ignore a comment like `// @public (together)`.  Let me know if you wish to discuss further.

**Comment by samreid** [comment]
Above I removed an occurrence of an object property that is no longer needed when using the tandem-style markup.

**Comment by samreid** [comment]
Removed another one.  All other `@public (together)` mentions (3 or 4 of them) in together are currently necessary.

**Comment by jbphet** [comment]
In principle, it still seems odd to me to have an open source library that we have said should be available and usable by organizations outside of PhET, and in that library have comments about another library that is *not* available to organizations outside of PhET.  This is bound to be confusing to any potential external users.  However, the practical reality is that we don't know of anyone other than PhET that is using this, so the debate is largely academic, and we have much larger fish to fry.  With that in mind, I'm closing this.
