### ISSUE TITLE
fix API for momentary buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#210]
Here's the constructor for RoundToggleButton:

`function RoundToggleButton( valueA, valueB, property, options )`

Here's the constructor for RoundMomentaryButton:

`function RoundMomentaryButton( onProperty, options )`

Similar for rectangular versions.  The API for momentary buttons should be the same as toggle buttons, since they are a form of toggle button, e.g.:

`function RoundMomentaryButton( valueA, valueB, property, options )`

RoundMomentaryButton is only used in 3 places, and RectangularMomentaryButton in 1 place. So now would be a good time to do this.

**Comment by pixelzoom** [comment]
The `valueA` and `valueB` parameters (and their doc) tell us nothing about how those values correspond to button state.  This should be fixed in RoundToggleButton and RectangularToggleButton, and I'll create a separate issue for that.  

So the constructors I'll use for momentary buttons are:

`function RoundMomentaryButton( upValue, downValue, property, options );`
`function RectangularMomentaryButton( upValue, downValue, property, options );`

**Comment by pixelzoom** [comment]
Done. Assigned to @jbphet for review.

**Comment by pixelzoom** [comment]
@jbphet can you get to this, or should I assign to someone else to review?

**Comment by jbphet** [comment]
For the most part this looks good to me.  My one caveat is that I personally prefer the parameter names of ```upValue``` and ```downValue```, as committed in https://github.com/phetsims/sun/commit/913e01dea7238de510d19151c418bc0a2ec2fa9d versus the names ```valueOff``` and ```valueOn```, as committed in https://github.com/phetsims/sun/commit/8b34cdf6276789f2dd9a00e70f2dee61c64a24ce.  I understand that @pixelzoom's goal is consistency with the toggle button API, but I don't think such consistency is essential and may even be confusing.  In one of the comments above @pixelzoom said, "The API for momentary buttons should be the same as toggle buttons, since they are a form of toggle button[.]"  I only partially agree with this.  Sure, a momentary button changes the value of a property between two different values, but *when* it does it is different from what I think of as a classic toggle button.  I think ```upValue``` and ```downValue``` are more descriptive and clear.

I could live with it as is, so I'll leave it to @pixelzoom to decide if he agrees with this argument.  If not, he can feel free to simply close the issue, since the rest of the changes have been reviewed and approved.

**Comment by pixelzoom** [comment]
A momentary button by definition have 2 states: 'off' and 'on'. E.g. the JSdoc in RectangularMomentaryButton:

> A rectangular momentary button: on when pressed, off when released.

The states are not 'up' and 'down', that's the pointer state.  So I'd prefer to leave the value parameters as `valueOff` and `valueOn`.

Closing.
