### ISSUE TITLE
need to know whether an item is visible in Carousel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#230]
In function-builder, I need to know whether an item is currently visible in the carousel. This is important for the "erase" button feature associated with the output carousel.  Items that are visible in the carousel will be animated back to the input carousel, while those that are not visible will be moved immediately to the input carousel.

**Comment by pixelzoom** [comment]
Work completed. Add `isItemVisible` and factored out `itemIndexToPageNumber`.  Feature is currently used by "erase" button for output carousel in Function Builder.

Assigning to @jbphet for review, since he's reviewed the last couple of enhancements to Carousel.

**Comment by jbphet** [comment]
The changes look reasonable.  However, the feature itself feels a little odd to me because I've never used the carousel in a way where items are added and removed.  Generally, I've used it more as a tool box sort of thing, where it contains creator nodes that stay on the carousel.  I could envision a case where the code would need to know whether the creator node corresponding to a given model element were visible, and in that case we'd want something more general, such as a method that took a test function as the parameter instead of a node, as "isItemVisible" currently does.  I don't have any current requirement for such behavior, so it probably isn't worth generalizing in this way at this time.  I'll assign this back to @pixelzoom to mull over the idea of making this more general, but he should feel empowered to close if he also feels that this isn't worth the effort unless and until we have a requirement for more general behavior.  Maybe we would just note the thought in a comment.

**Comment by pixelzoom** [comment]
Discussed with @jbphet via Skype, sounds like this approach is sufficiently general for now. Closing.
