### ISSUE TITLE
Add a multiple arrow button

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/sun#265]
From https://github.com/phetsims/forces-and-motion-basics/issues/199 there was a request for a button with two arrows, which looks like a fast forward button.  This seems like useful thing to add to sun.

We could
 1. Add a new type that supports a button with multiple arrows
 2. Generalize ArrowButton to support N arrows

Option 2 seems very easy, an optional parameter could be passed in to specify the number of arrows for the button, with the default being 1.

**Comment by jessegreenberg** [comment]
With the above commit, ArrowButton can have N arrows.  Each arrow in the button has the same shape and styling.  It is being used in forces-and-motion-basics, I tested in a few other sims, and ran test server.

@pixelzoom would you mind reviewing https://github.com/phetsims/sun/commit/f2bd9d60cd649fc2c873815bef82a7bcb590ceb2 since you were the original author of ArrowButton?

**Comment by pixelzoom** [comment]
For purposes of discussion, here's what ArrowButton looks like in forces-and-motion-basics, with these options:

```js
numberOfArrows: 2,
arrowHeight: 20,
arrowWidth: 8.660254037844386,
```

![screenshot_196](https://cloud.githubusercontent.com/assets/3046552/18529604/046deba0-7a8b-11e6-97b2-4a312f1b6927.png)

**Comment by pixelzoom** [comment]
(1) The current implementation creates a Path node for each arrow.  It would be more efficient to create a single Path with one Shape.  Not a big deal unless you have a lot of these buttons, or (unlikely) a button with a lot of arrows.  But I thought I'd mention it anyway.

(2) The bigger issue is (I think) how this looks.  In FAMB, to my eye, it looks very odd that the double arrows have different dimensions than the single arrows.   A more conventional look would be something like the screenshot below, which I hacked together using a negative value for `arrowSpacing`. So we may want to have a more general discussion about what this type of control should look like, because (presumably) it will be useful elsewhere.

![screenshot_197](https://cloud.githubusercontent.com/assets/3046552/18529926/4c1aecfe-7a8c-11e6-936f-0069e06f5378.png)

**Comment by pixelzoom** [comment]
(3) In FAMB, should the double arrow buttons be swapped with the single arrow buttons? It seems like the smaller increment buttons should be closer to the value.

**Comment by jessegreenberg** [comment]
Thanks @pixelzoom, in response to the above points:
 1. Good point.  Once point 2 is sorted out, I can look at look into using a single path for the arrows.
 2. There is a discussion about the arrow styling in https://github.com/phetsims/forces-and-motion-basics/issues/199, I will move comments and recommendations there.
 3. Same as 2, moving to https://github.com/phetsims/forces-and-motion-basics/issues/199

**Comment by jessegreenberg** [comment]
The commit above should handle points (1) and (2) in the review comment https://github.com/phetsims/sun/issues/265#issuecomment-247153292.  Button content now uses a single path.

Here is an example of what the arrows look like now, with the last four buttons on the right showing examples with extra optional spacing:
![arrow-buttons](https://cloud.githubusercontent.com/assets/6396244/18973330/32ad4c88-865a-11e6-8978-a251028bf009.PNG)

Would you mind reviewing once more @pixelzoom?

**Comment by pixelzoom** [comment]
👍 Closing.
