### ISSUE TITLE
Convert from PropertySet to Property

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#274]
Per https://github.com/phetsims/axon/issues/102...  Convert from PropertySet to Property.

PropertySet is only used in ButtonModel, but chasing down all usages of its Properties may be difficult.

**Comment by jbphet** [comment]
Adding @ariel-phet to list of assignees to help with prioritization (and because he asked me to).

**Comment by ariel-phet** [comment]
@jbphet lets discuss once SOM is in QA testing

**Comment by jbphet** [comment]
I have committed code for this and done a fair amount of testing on my own.  This affects every simulation, so some additional testing is warranted.  Assigning to @phet-steele to test.  I suggest running the automated fuzz testing, fuzz testing the phet-io sims, and manually spot checking a bunch of sims - particularly those with lots of buttons - for correct operation of all button-related functionality.

**Comment by pixelzoom** [comment]
This looks like a bug, AreaBuilderGameView line 906:

```js
      if ( this.model.currentChallenge.checkSpec === 'areaEntered' ) {
          this.checkAnswerButton.enabled = this.numberEntryControl.keypad.valueStringProperty.value.length > 0;
        }
        else {
          this.checkAnswerButton.enabled = this.model.simSpecificModel.shapePlacementBoard.areaAndPerimeter.area > 0;
        }
```

Shouldn't `checkAnswerButton.enabled =` be `checkAnswerButton.enabledProperty.value =` ?

**Comment by pixelzoom** [comment]
Ah, never mind...  `this.checkAnswerButton.enabled` is using the ES5 setter of ButtonView, not the enabledProperty of ButtonModel.  These separation of view and model continues to mess me up.

**Comment by pixelzoom** [comment]
sun is failing lint.

**Comment by pixelzoom** [comment]
@jbphet said in Skype:
> I left .enabled on the buttons and changed the underlying buttonModel to have enabledProperty.  My thinking is that most UI components have this sort of ES5 setter/getter, so it would be good to be consistent with that.  Seem reasonable?  Did you see this by inspection or through testing? 

Via inspection. But then I realized that `this.checkAnswerButton.enabled` is using the ES5 setter of ButtonView, not the enabledProperty of ButtonModel.  These separation of view and model continues to mess me up.

**Comment by pixelzoom** [comment]
I should also point out that we recently decided on a pattern for enabling/disabling UI components. And this doesn't conform.

**Comment by jbphet** [comment]
@pixelzoom and I discussed this.  The crux of the issue was to move the buttons off of PropertySet, and I kept API to the buttons the same, so the ES5 getter/setter for button state (which is separate from the underlying button model) was left in place.  We should probably deal with the inconsistency with how enabled/disabled is handled at some point, but we agreed that this is outside the scope of this issue.  The issue related to enabled/disabled handling is https://github.com/phetsims/sun/issues/257.

**Comment by pixelzoom** [comment]
@jbphet When you moved ButtonModel away from PropertySet, that broke somethings, because ButtonModel no longer has a dispose function (which it inherited from PropertySet).

E.g. in this code from `unit-rates.EditNumberDisplay`, where `editButton` is a RectangularPushButton:

```js
    dispose: function() {
      ...
      !assert && this.editButton.dispose();  // SUN buttons dispose fails when assertions are enabled - see sun/#212
      ...
    }
```

`RectangularPushButton.dispose` calls `PushButtonModel.dispose`, which calls ButtonModel.dispose.  And `ButtonModel.dispose` no longer exists because it's not extending PropertySet.  So line 96 of PushButtonModel:

```js
96  ButtonModel.prototype.dispose.call( this );
```

...fails with: 

> PushButtonModel.js?bust=1480467093716:96 Uncaught TypeError: Cannot read property 'call' of undefined(…)"

**Comment by pixelzoom** [comment]
You also didn't implement `reset` for the 3 Properties owned by ButtonModel.

**Comment by pixelzoom** [comment]
`ButtonModel.prototype.dispose.call( this )` is invoked by these subtypes:

MomentaryButtonModel
PushButtonModel
ToggleButtonModel

**Comment by pixelzoom** [comment]
I implemente `dispose` and `reset` for ButtonModel. @jbphet please review the above commit.

**Comment by jbphet** [comment]
@pixelzoom - thanks for taking a stab at these.  There are a couple of things I'd like to discuss about the changes.

First, the idea of having a reset function seems a little suspect to me since this model is generally driven by input events.  If the reset were called when a pointer was over a button and/or down on a button, it could potentially confuse the state machine.  I could see this happening in a multi-touch scenario.  What do you see as the motivation for having reset?  Is it for backward compatibility with PropertySet?

Second, the dispose function now exists but is essentially stubbed.  The three properties in ButtonModel are internally created, not passed in, so I'm thinking the function should call `dispose` on those properties.  The `Property.dispose()` method just checks that there are no listeners (and asserts of there **are** some), so I suspect that the net effect of doing this would be that we would see assert failures when this was called.  This may open a can of worms - see https://github.com/phetsims/sun/issues/212 - but perhaps it is time to address it.  I could carve out some time and look at distributing the dispose functions into the various places where the properties are linked, or try out the proxy pattern proposed in https://github.com/phetsims/sun/issues/212.  Do you agree at least that the dispose function should call the individual property dispose functions?

**Comment by pixelzoom** [comment]
(Ignore above 2 commits. I misunderstood something, then reverted.)

If you don't think there's ever going to be a need to reset a button, then feel free to remove `reset` from ButtonModel. I added it for backward compatibility with PropertySet.  Before doing so, please verify that there are no clients relying on it (as they were with `dispose`).

Re `dispose`... Yes, calling `dispose` on the Properties sounds like the right thing to do. I didn't do that because my goal was to fix the crash in Unit Rates, not resolve the issue of memory leaks in sun buttons (https://github.com/phetsims/sun/issues/212).

**Comment by pixelzoom** [comment]
@jbphet What do we need to do to close this?

**Comment by jbphet** [comment]
Thanks for the ping.  I'll take a look at it on Friday of this week (currently my common code day) and see what needs to be done and if I can just do it.

**Comment by jbphet** [comment]
I went ahead and removed the reset function.  I think allowing reset of the button model would open a can of worms.  It was previously available as a side effect of descending from `PropertySet`, but I am fairly certain it was never used.  Having it explicitly implement would potentially indicate to future users of this class that it can and should be reset in some situations, and I don't want to send that message.

I've tested this so far by:
+ manually interacting with the Sun button demo
+ fuzz testing the Sun button demo
+ manually interacting with and then fuzz testing (for ~30 seconds) four sims, chosen because they were mostly done by different developers, the sims being:
  + Forces and Motion Basics
  + Rutherford Scattering
  + Hooke's Law
  + Area Builder

I'll monitor the next few rounds of automated testing too in order to make sure no issues show up there.

**Comment by jbphet** [comment]
I just checked the results of the automated testing and I'm not seeing any instances of new errors that appear to be related to the removal of the `reset` method from `ButtonModel.js`.

**Comment by jbphet** [comment]
I'd like to get some input from the developers as to whether it really makes sense to call the `Property.dispose` method from the `dispose` method of a button.

**Comment by pixelzoom** [comment]
If the Property is owned by the button, then calling `Property.dispose` will verify that there is nothing observing a disposed button.  That would also mean that observers would need to `unlink` before calling dispose on the button.

**Comment by pixelzoom** [comment]
... that said.  I don't believe the most (any?) common-code components call `dispose` on their owned Properties.  And if a Property is passed in via options, determining whether the component owns the Property is problematic.   So I'm not sure what to recommend for buttons.

**Comment by samreid** [comment]
We discussed clearing listeners from a disposed Property instead of asserting an error.

**Comment by samreid** [comment]
So the new dispose will be (with added documentation still to be added):

```js
    // @private
    this.disposeProperty = function() {
      self.changedEmitter.listeners.length = 0;
      options.tandem && options.tandem.removeInstance( self );
    };
```

**Comment by samreid** [comment]
And we should remove the `PHET_IO_FUNCTION` everywhere.

**Comment by samreid** [comment]
@pixelzoom recommends to scan through property creation in common libs and make sure that Properties are disposed.  We have to look for `new Property` and other Property subclasses such as `new BooleanProperty`, etc.

**Comment by pixelzoom** [comment]
Would be nice to wrap this up, it's been open too long for a high-priority issue.

In https://github.com/phetsims/axon/issues/124, we change Property.dispose to unlink all listeners. 

Has `PHET_IO_FUNCTION` been removed from everywhere?

**Comment by samreid** [comment]
> Has PHET_IO_FUNCTION been removed from everywhere?

I don't see that term in our codebase in master.

**Comment by jbphet** [comment]
Yes, I removed usages of PHET_IO_FUNCTION (there were only one or two usages).

**Comment by jbphet** [comment]
The only remaining work item on this is from comment https://github.com/phetsims/sun/issues/274#issuecomment-299270120 where it says, "[S]can through Property creation in common libs and make sure that Properties are disposed".  I can do that tomorrow, Friday June 8 2017, since that is my common code day.

**Comment by samreid** [comment]
One option that was brought up: each UI component would create their own Property instances.  If a parameter is passed in, it could be *linked* to the UI component property.

**Comment by samreid** [comment]
Closing, the outstanding issues will be tracked in the above 2 issues.
