### ISSUE TITLE
PhET-iO API for PushButtonModel.isFiringProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#321]
We will need to update the sonification wrappers, the PushButtonModel.dispose function, UtteranceQueue and possibly other things!

We'll need to coordinate the sonification wrapper updates with new deploys of the sims they use, so they don't go through a broken period of time.

**Comment by zepumph** [comment]
Commits for this issue:
https://github.com/phetsims/sun/commit/64bcf7ece2a4e3a12accf3cef0c81fb5f04756fc
https://github.com/phetsims/scenery-phet/commit/dc455fb69e90cac1e45dd0d3e4bc0e894a90285f

I haven't touched the sonification wrapper yet, but that won't matter until we republish next week. I will make sure I cover this as part of integrating phetsims/ohms-law#92 into the sonification wrapper. Closing

**Comment by zepumph** [comment]
Reopening because phetsims/phet-io#1225 made us question the practice of having a button model isFiringProperty, but turning it off for all instances except for the resetAllButton. 
@samreid and I think that the best way to proceed is to have the buttonModel.isFiringProperty not be instrumented, and then have the ResetAllButton create a mirror property that is instrumented.

**Comment by zepumph** [comment]
This is looking pretty good. The only problem I can see is that it doesn't nest in the data stream:
```
{
  "messageIndex": 143,
  "eventType": "model",
  "phetioID": "buildAnAtom.atomScreen.view.resetAllButton.isFiringProperty",
  "componentType": "TProperty.<TBoolean>",
  "event": "changed",
  "time": 1510006377701,
  "parameters": {
    "oldValue": false,
    "newValue": true
  }
}
{
  "messageIndex": 144,
  "eventType": "user",
  "phetioID": "buildAnAtom.atomScreen.view.resetAllButton",
  "componentType": "TPushButtonModel",
  "event": "fired",
  "time": 1510006377701
}
{
  "messageIndex": 145,
  "eventType": "model",
  "phetioID": "buildAnAtom.atomScreen.view.resetAllButton.isFiringProperty",
  "componentType": "TProperty.<TBoolean>",
  "event": "changed",
  "time": 1510006377703,
  "parameters": {
    "oldValue": true,
    "newValue": false
  }
}
```

**Comment by zepumph** [comment]
@samreid  please review commit and comment.

**Comment by samreid** [comment]
All looks good, thanks @zepumph, closing.

**Comment by zepumph** [comment]
After discussing this more with @jbphet and @samreid and @chrisklus. Things may have changed in the last 2 years.

We found that instrumenting the reset all button's `isFiringProperty` for PhET-iO helped in the sonification wrapper, but we are wondering if we need to instrument this at all anymore? We already have a `firedEmitter` in `PushButtonModel`.  This really boils down to a PhET-iO design question. We want to know which if the following is best:
* No instrumented `isFiringProperty`, because clients can just use the `firedEmitter` to fire listeners as needed. Note that this wouldn't support cases like turning off sound in the sonification wrapper, even though that isn't a use case we need for that deprecated repo now.
* Keep the isFiringProperty instrumented just for `ResetAllButton`. To me this feels weird. there is duplicated code just to expose `isFiringProperty` on a subset of push buttons. I would like to remove the derived property in `ResetAllButton`.
* Instrument the isFiringProperty in PushButtonModel. This would add the Property to every push button. Is this needed? Is this overkill for the slight value increase from the peer emitter.

**Comment by zepumph** [comment]
In phet-io design meeting today, we decided to get rid of `isFiringProperty` on resetAllButton, because it isn't being used right now on master. 

@kathy-phet mentioned that if in the future we do need it, then we can add it back in. 

@pixelzoom recommended that if the need arises, we should investigate another solution that is less "workaroundy" (not his words). Perhaps by holding "reseting" state in Property for when `reset` is firing.

**Comment by zepumph** [comment]
There was a dependency on this for the lab-book wrapper, and I found it easily mapped over to use by the firedEmitter. This makes me feel even better about getting rid of this. Removed above; tested in wrappers in phet-io brand. All looks good. Closing.
