### ISSUE TITLE
AccessibleSlider decimal places

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/sun#368]
In area-model, the number of decimal places is dependent on the scene, and the a11y sliders are used across multiple scenes.

Should AccessibleSlider be refactored so that accessibleDecimalPlaces is a mutable parameter (has getter/setter)? Presumably we don't want to support a Property for that?

**Comment by zepumph** [comment]
That sounds good to me, I too think a Property could be overkill.

**Comment by zepumph** [comment]
I know this is an old issue, but note that we no longer support decimal places for accessible slider, instead we are just using a map value function. I just added a setter for that a11yMapValue option above. Will that work for you?

**Comment by zepumph** [comment]
This issue is very old and our value mapping has been going well for quite some time. I feel good about closing this issue, @jessegreenberg will you give it a spot check before closing.

**Comment by jonathanolson** [comment]
If I pass in `supportsInteractiveDescription=true`, it looks like the proportion line in the 100x100 screens is going up by 1, due to a `Utils.roundSymmetric`, where it should be going up by 10. So this seems buggy in area-model at least.

**Comment by zepumph** [comment]
I'm not sure I understand, isn't that just because of the keyboardStep in ProportionalPartitionLineNode? That should be customizable based on the screen it is created in?

**Comment by jonathanolson** [comment]
It's because the step of ProportionalPartitionLineNode needs to effectively dynamically change, based on the scene (not screen).

So when on the 20x20 scene, it should step by 1. When on the 100x100 scene, it should step by 10. So it will need to be mutable.

**Comment by zepumph** [comment]
Ok, so the issue seems to be 2 items. Both involve using the keyboard to drag the orientation-specific triangles (ProportionalPartitionLineNode)

In http://localhost:8080/area-model-decimals/area-model-decimals_en.html?brand=phet&ea&debugger&supportsInteractiveDescription=true

The decimal will ALWAYS round up to 1, most likely because of `Utils.roundSymmetric`.


Then in http://localhost:8080/area-model-multiplication/area-model-multiplication_en.html?brand=phet&ea&debugger&supportsInteractiveDescription=true when set to 100x100, the keyboard step is still just 1, so it doesn't snap to the grid.

@jonathanolson. Could we get by with dynamically setting the keyboard step with setKeyboardStep? That will at least solve the second one I think.

**Comment by jonathanolson** [comment]
That works great! Handled above. @zepumph does this work nicely for you? Can we close? (I tested the 3 configurations)
