### ISSUE TITLE
DemoScreenView can leak CPU/memory

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#386]
DemosScreenView can select animated components, but doesn't have a dispose or unregister phase when a component is deselected.  Hence components that animate or attach listeners elsewhere will leak.  Discovered during https://github.com/phetsims/wave-interference/issues/111

These demos are not given to clients and are for internal testing only.  It seems OK to proceed as-is, as long as other developers are aware that switching back and forth between components a lot could cause performance or memory issues.

**Comment by samreid** [comment]
When the user selects “Component X” from the dropdown menu, then selects “Component Y” from the dropdown menu, the instance of type Component X is never disposed (that I know of).  Sorry that I phrased it confusingly.

@pixelzoom replied:

> Agreed that DemoScreenView should dispose (if implemented) things that it instantiates.

**Comment by samreid** [comment]
Assigned for developer meeting so we can choose who should work on this, when and with what priority.

**Comment by pixelzoom** [comment]
Some relevant Slack conversation:

> John Blanco [1:10 PM]
I just tried the sun demo, and when one switches back and forth between components, the original component seems to be retained, not recreated (I switched back and forth between a carousel and an HSider, changing the state of each).  If the components stay around, no dispose would be necessary, right?
> 
> Sam Reid [2:04 PM]
In Griddle, it would be creating and animating a plot that is hidden.  DemosScreenView has this code:
      ```if ( oldDemo ) {
        oldDemo.node.visible = false;
      }```
I wonder if we use dipose there instead, if DemosScreenView + fuzzMouse could be used as a memory leak tester?
> animating a plot that is hidden
> 
> Or potentially animating multiple invisible plots.

I'm not sure that DemosScreenView should be to test dispose, or that it's current behavior should be changed at all.  Perhaps it's would be better to follow the pattern used with other components, and have controls (buttons, etc.) in the griddle demo for switching between (and managing memory of) plots.   And if plots that are not visible are continuing to animate, that seems like a separate problem.

**Comment by jessegreenberg** [comment]
> I'm not sure that DemosScreenView should be used to test dispose

I agree, especially since we already have MemoryTestsScreenView. In https://github.com/phetsims/wave-interference/issues/111 I didn't see how @samreid encountered this, in your testing were you able to observe that performance slowed down? If not, I don't think that it is too important that DemosScreenView be leak free.

**Comment by jonathanolson** [comment]
To me, it would be good to (sometime) fix the leaks in demos, but it's probably not a particularly high priority.

**Comment by samreid** [comment]
> I didn't see how @samreid encountered this, in your testing were you able to observe that performance slowed down?

I didn't observe any slowing down or other symptoms, and I think that would be unlikely during normal usage.

**Comment by samreid** [comment]
Actually, if the components are not re-created, then it is not a very bad leak at all.  The leak is "capped" at the number of creatable components.

**Comment by pixelzoom** [comment]
@jonathanolson said:
> To me, it would be good to (sometime) fix the leaks in demos, but it's probably not a particularly high priority.

The description of this issue has been confusing (here and in Slack).

My understanding is that the current demos (with the exception of `MemoryTestsScreenView`) do not dynamically create components. So I'd be surprised if there were significant leaks.   I suspect that it's more likely that @samreid encountered a leak when attempting to use this in a new griddle demo.   

@samreid Could you please identify which demos are currently leaking, and which components you suspect are the culprits?

**Comment by samreid** [comment]
I was surprised to find that components were cached instead of re-created.  There is a mild CPU inefficiency in griddle/js/demo/GriddleDemoScreenView.js because nonvisible graphs are still animated.  This is a noncritical problem that may not need to be solved.

@pixelzoom said:

> My understanding is that the current demos (with the exception of MemoryTestsScreenView) do not dynamically create components

Thanks, I've learned that.

@pixelzoom said:

> Agreed that DemoScreenView should dispose (if implemented) things that it instantiates.

That may be nice one day, but I'm not sure whether it's worth the time to change it at the moment.

**Comment by jbphet** [comment]
Discussed this today in the dev meeting and decided that the benefit of changing the demo screen view to call dispose is worth the implementation cost, which was estimated at 15 min.  @pixelzoom said he'd do it.

**Comment by pixelzoom** [comment]
Chris Malley [1:35 PM]
Before I push changes to DemoScreenView, there is one possibly important feature that we’ll lose by disposing of (rather than caching) demo components.  If/when you return to that component, it will be in it’s initial state, and any “work” that you did playing with that component will be lost.  I frankly don’t care one way or the other.  If no one objects, I’ll push in ~10 minutes.


Jesse Greenberg [1:36 PM]
That seems totally fine to me

John Blanco [1:53 PM]
No objections here.

Sam Reid [1:56 PM]
Sounds good, thanks

Chris Malley [1:57 PM]
I’m going to future-proof with a caching option.

**Comment by samreid** [comment]
Changes look good.  I tested with `cacheDemos: true` and `cacheDemos: false` and the behavior was correct.  I also leveraged the dispose callback in griddle to remove the listeners and confirmed they were being removed properly.  Closing.

**Comment by pixelzoom** [comment]
Reopening and putting on the dev project board. 

In Slack today, @jbphet pointed out that things are still not properly disposed in demo applications.  This is because most "demo" functions (`demoPushButtons`, `demoRadioButtons`, etc.) are factory functions that are not designed to properly dispose of what they create.   It will be a lot of work to address this.  I don't think it's worth it, and I don't think that the demo applications are the proper place to be testing `dispose`.

**Comment by jbphet** [comment]
I've added a comment to `DemoScreenView` to prevent others from having the same misunderstanding that I had when I looked at the code.

**Comment by marlitas** [comment]
JB: DemoScreenView is not a place to test dispose. If you would like to do that create a subclass.
CM: Would be a lot of work to get DemoScreenView to dispose properly and doesn't seem worth it.

PSA delivered. Closing.
