### ISSUE TITLE
why is toggleEmitter needed in Checkbox?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#395]
Encountered while working on https://github.com/phetsims/sun/issues/393.

`toggleEmitter` was added to Checkbox by @zepumph in https://github.com/phetsims/sun/commit/80548d6c4b0eccbdd8ede835cceee5f754aae9a2 for https://github.com/phetsims/phet-io/issues/1345.

Why is `toggleEmitter` needed?  
Doesn't `property` provide the identical information (that is, the state of the checkbox)?   
Why does Checkbox set `property` indirectly via `toggleEmitter`? 
Why can't `fire` set `property` directly?
Why is there no `toggledEmitter.emit1` when the client changes the value of `property`? (which _will_ result in the checkbox changing state!)

**Comment by zepumph** [comment]
>Why is toggleEmitter needed?

It was added for phet-io in a growing effort to simplify the phet-io api. Instead of needing many custom phet-io types like `CheckboxIO`, which only exist to document and validate that the Checkbox can emit a "toggled" event, we pass that logic over to Emitter, which is already insntrumented to support this same functionality for the data stream, and with proper/consistent documentation etc. We have been utilizing this approach throughout sun/scenery-phet, and it has been working very nicely in the context of phet-io. 

>Doesn't property provide the identical information (that is, the state of the checkbox)?

It conveys simlar info, but in general we are trying to have a data stream that conveys the whole MVC stack, i.e controller: scenery input events and listener events, view: the component firing, and model: the corresponding property changing. In addition each phet-io event has a phetioEventType of either 'model' or 'view' that can be used to gain a better understanding of this differential.

Why does Checkbox set property indirectly via toggleEmitter?

By "firing" via an Emitter listener, we don't have to copy phetioEvent implementation into this file, i.e. by making Checkbox an instrumented type, with a TypeIO, that extends PhetioObject, that has to implement `this.phetioStartEvent` and `this.phetioEndEvent` to surround the fire logic appropriately. All of this is already done by Emitter. As a result, this pattern has allowed us to clean up many unneeded TypeIOs while simplifying the API and making it more consistent.

>Why is there no toggledEmitter.emit1 when the client changes the value of property? (which will result in the checkbox changing state!)

Hmm I'm not sure that is necessary, because it may yield a confusing data stream (for the model to change the view). @samreid what do you think?

**Comment by pixelzoom** [comment]
Yes, update the doc.

And register a general concern about "complexity" if this is the direction that PhET-iO is taking for all UI components.

**Comment by zepumph** [comment]
>And register a general concern about "complexity" if this is the direction that PhET-iO is taking for all UI components.

Well I would say that in the context of PhET code it is a bit more complex, but all around, given the amount of phet-io specific code that is otherwise expected to mimic this functionality without an Emitter, this pattern is quite a bit simpler @pixelzoom. I'm happy to discuss further or brainstorm other options if you feel this is actionable worry.

**Comment by zepumph** [comment]
@pixelzoom I'm not sure what more this issue needs. Do you have any other questions or concerns to discuss? Otherwise my vote would be to close.

**Comment by pixelzoom** [comment]
@zepumph you said:
> How about an update to the doc like: Emits when user input caused the checkbox to toggle

That does not appear to have been done.

**Comment by zepumph** [comment]
Shoot, done above.
