### ISSUE TITLE
instrument ComboBox better

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#405]
While working on https://github.com/phetsims/tandem/issues/62, we found that there was weird buggyness in how the buttonNode was being instrumented, but the tandem set to be "enabled: false". This was the only place in the project where tandem.enabled was being used. 

We should make sure that we are getting the appropriate events/customizations fro ComboBox.

**Comment by samreid** [comment]
I'm working on https://github.com/phetsims/sun/issues/396 and found that ComboBox should probably be using one FireListener per button rather than batching them all into a single listener.

**Comment by samreid** [comment]
Not used in graphing quadratics or faradays-law.

**Comment by samreid** [comment]
> the tandem set to be "enabled: false". This was the only place in the project where tandem.enabled was being used.

`tandem.enabled` was removed in https://github.com/phetsims/tandem/issues/62

Hence the remaining work for this issue is:
- [ ] weird buggyness in how the buttonNode was being instrumented (may have been addressed by removing tandem.enabled)
- [ ] We should make sure that we are getting the appropriate events/customizations fro ComboBox.
- [ ] ComboBox should probably be using one FireListener per button rather than batching them all into a single listener.

**Comment by samreid** [comment]
In discussion with @chrisklus, we concluded that it seems best to schedule a PhET-iO design for ComboBox before deciding how to approach the remaining work for this issue.  For instance, if we decide that PhET-iO clients should not be able to disable (make unpickable/transparent) individual elements in the popup box, we may prefer a single FireListener for the entire ComboBox.  Conversely, if we keep customization of individual elements, it may make more sense for each of them to have their own FireListener.

Perhaps next time we PhET-iO design a simulation with ComboBox it would be a good idea to discuss this issue.

**Comment by samreid** [comment]
"meeting:phet-io" label is to make sure other team members are aware of the need for ComboBox PhET-iO design, probably the next time we have a PhET-iO design for a sim with a ComboBox.

**Comment by pixelzoom** [comment]
FYI, things are pretty broken right now.  https://github.com/phetsims/sun/commit/f75f5305ca9b67dae9a6d9892eb0ea95aec681c3 is passing `tandem` to the wrong constructor (ComboBoxItemNode instead of ButtonNode).  ButtoNode is being passed all of ComboBox's options, which is bad news when those are phetio options.   ButtonNode was blowing away any tandem that it was passed (fixed in https://github.com/phetsims/sun/commit/e0d1a3d874d66703bbaa3c8208f8d011a7349d4b).

Marking as high priority and "blocks-publication", because this is in no shape for production.

**Comment by pixelzoom** [comment]
I see that "Finish conversion to ES6" was check off in https://github.com/phetsims/sun/issues/405#issuecomment-438741993.  Not even close, I'm going to uncheck it.  There's no use of `class`, and it's still using `inherit`, `var`....

**Comment by pixelzoom** [comment]
https://github.com/phetsims/sun/issues/422 is a prerequisite to addressing this issue properly.

**Comment by pixelzoom** [comment]
In Slack conversation, we decided to revert the previous 2 commits.

**Comment by zepumph** [comment]
@pixelzoom why is this High priority after we reverted the commits above?

**Comment by pixelzoom** [comment]
Because presumably one of our most important UI components should be implemented correctly?

**Comment by pixelzoom** [comment]
Because (presumably) one of our most important UI components should be implemented correctly, instead of relying on a buggy hack.

**Comment by pixelzoom** [comment]
In the previous commit, I added a bunch of TODOs related to this issue.

**Comment by pixelzoom** [comment]
ItemNode instances are now shared between the ComboBox's list and button, See https://github.com/phetsims/sun/issues/428#issuecomment-451588040. This changed the scenegraph structure in major ways.  And #430 (factor out ListNode) will surely result in further changes. So instrumentation of items needs to be revisited.

**Comment by pixelzoom** [comment]
Re:

> * change the text name of elements, like "mystery object" or "object 1"

It's also important to note that this operation is generally not specific to ComboBox.  ComboBox displays ComboBoxItems, with include the visual representations (Nodes) that corresponds to values.   In the case where those visual representations contain text, we want to change the text at the source - NOT after the Nodes have been assembled, and most definitely NOT after they have been provided to the ComboBox.

**Comment by samreid** [comment]
We previously experimented with a PhET-iO mode where objects were customized as they were created, but it was ultimately removed it because it was incompatible with subtyping.  We could open a new investigation for this, or look at using query parameters (or another upstream mechanism) to accomplish this.

@jonathanolson previously promoted making our UI components more mutable, and we have done that in some cases, such as changing colors.  @pixelzoom said often it is simpler to dispose an entire UI component and create a new one, but @jonathanolson pointed out that can damage the state of interaction with an in-use component.

> we want to change the text at the source - NOT after the Nodes have been assembled, and most definitely NOT after they have been provided to the ComboBox.

@pixelzoom also pointed out that it may be possible to change text after UI component construction as long as we correctly set `maxWidth` on individual components so the layout isn't disturbed.

> we want to change the text at the source

One way to change the values at the source and have the changes reflected downstream would be to model them as axon Properties.  This is what we typically do for other cases.

**Comment by pixelzoom** [comment]
But again, since I'm not sure everyone understands.  Regardless of whether UI components are mutable, text strings should not be changed at the UI component.  We use MVC, so in general there may be multiple views of one text string.  So the correct place to make the change is at that one text string, not in each UI component.

**Comment by pixelzoom** [comment]
> @pixelzoom also pointed out that it may be possible to change text after UI component construction as long as we correctly set `maxWidth` on individual components so the layout isn't disturbed.

If we're going to rely on `maxWidth` to solve this problem, then we should consider that we're typically using `maxWidth` only for translated string.  If the PhET-iO client is allowed to change non-translated text (as was proposed for the formula in Beer's Law Lab), then we'll potentially need to start setting `maxWidth` for _all_ text.  And we'll need a way to test, since `stringTest` won't expose problems with non-translated strings.

**Comment by pixelzoom** [comment]
FYI, due to the "listbox" terminology that we decided on in #440, methods and event names in ComboBox and ComboBoxIO have been changed as follows:

`showList` -> `showListbox`
`hideList` -> `hideListBox`
`'popupShown'` -> `'listboxShown'`
`'popupHidden'` -> `'listboxHidden'`

**Comment by samreid** [comment]
4/5 of the main (non-brainstorm) requests in https://github.com/phetsims/sun/issues/405#issuecomment-455431908 are complete.  I recommend to close this issue and open an issue for the remaining part.  @pixelzoom anything else for this issue?

**Comment by pixelzoom** [comment]
I count 3/5 that are completed.  These 2 are not done:

* #458, change the text name of elements, like "mystery object" or "object 1"
* #451,  Put it in a mode where you get rid of the triangle and line

But I'm OK with closing this and tracking the remaining tasks in their respective issues. 

A general question...  If issues like this one are the way that we're going to develop PhET-iO API requirements for common-code UI components, then how will we refer to this documentation in the future?  Do I need to find this issue and then try to synthesize the decisions from the comments? Should the decisions made herein be documented in ComboBox.js? ComboBox.md? somewhere else?

**Comment by pixelzoom** [comment]
@zepumph, @samreid, and I address the remaining TODO comments.   So I'm OK with closing this if @zepumph and @samreid agree.

**Comment by zepumph** [comment]
Sounds great. Thanks all.
