### ISSUE TITLE
memory leaks in Dialog

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#432]
Multiple leaks in joist.Dialog:

``` js
97  content.addEventListener( 'bounds', updateTitlePosition );
98  titleNode.addEventListener( 'localBounds', updateTitlePosition );
...
133 options.title.addEventListener( 'bounds', updateClosePosition );
```

Dialog doesn't own any of these things that it's adding listeners to; `content` is a constructor argument, and `titleNode` is an alias for `options.title`. Dialog also has no `dispose` function to remove the listeners, so it would technically fail a code review.

Assigning to @ariel-phet to prioritize and assign.

**Comment by jbphet** [comment]
Memory leaks in dialogs appears to be the main cause of the issue reported for blackbody-spectrum in https://github.com/phetsims/blackbody-spectrum/issues/72.  Here are a couple of screenshot from the memory profile comparison:

![image](https://user-images.githubusercontent.com/3082831/53051808-54727900-345a-11e9-9bbb-9335372d3f3f.png)

![image](https://user-images.githubusercontent.com/3082831/53051888-8aaff880-345a-11e9-81a6-7a7171b2b6fc.png)

I put a `debugger` statement in `Dialog.disposeDialog()`, and it didn't seem to get hit during ~20 seconds of fuzz testing nor during directed testing where I opened and closed dialogs manually via the PhET menu.  Maybe it's just a matter of calling this function when dialogs go away.

Labeling for dev meeting to see if we can assign someone to follow up on this.  It's not a huge memory leak, but we should fix it so that developers aren't spending time tracking this down for every sim that they publish.

**Comment by pixelzoom** [comment]
@jbphet I don't see any sim-specific Dialogs in blackbody-spectrum, so I'm guessing that the Dialogs that you're referring to in the previous comment are exclusively from the PhET menu.  If that's the case, then this is not specific to blackbody-spectrum and is impacting all sims.

**Comment by pixelzoom** [comment]
@ariel-phet this issue is still assigned to @andrealin.  Should it be reassigned?

**Comment by jessegreenberg** [comment]
In https://github.com/phetsims/joist/issues/424 Dialogs from the PhET menu were made to exist for the life of the sim which is why `dispose` is not called on them. Callbacks in PhET menu buttons look like
```js
          if ( !updateDialog ) {
            var phetButton = sim.navigationBar.phetButton;
            updateDialog = new UpdateDialog( phetButton );
          }
          updateDialog.show();
```

**Comment by pixelzoom** [comment]
Hmmm...  If PhET menu dialogs are persistent, then I wonder what dialogs @jbphet is referring to in blackbody-spectrum.  https://github.com/phetsims/sun/issues/432#issuecomment-465337561 seems to indicate UpdateDialog.

**Comment by pixelzoom** [comment]
2/21/19 dev meeting:
* @jbphet will look into this.

**Comment by jbphet** [comment]
I tested this using the "Blast" example sim, since it has very little going on that would cause memory to be allocated.  I'll add details below, but my conclusion is that the dialogs are not leaking memory, they just take a while to allocate all that they use.  This was done on master as of today.

Below is a screenshot of the rate of leakage on blast.  There does seem to be a slow leak during fuzz testing, but when I compared the memory snapshots and spot checked a number of the additional allocations, they all seemed to be associated with Scenery pools.  The screenshot shows memory values at 0-5 min of fuzz test sampling at every minute, and then one last snapshot after stopping the test.

![image](https://user-images.githubusercontent.com/3082831/53526579-ddfcf900-3aa1-11e9-9121-561373499b50.png)

I ran a second test where I started the sim, brought up the dialogs that are available from the PhET menu, recorded and snapshot, brought up the dialogs again, and recorded another snapshot.  Again, there was some memory allocated, but it all seemed traceable to Scenery pools.

I'm not sure where to go next with this, so I'll mark for dev meeting and we can collectively decide.

**Comment by pixelzoom** [comment]
Potential memory leak for `isShowingProperty` #369 fixed in the above commit.  Since it's `@protected`, subclasses might add a listener that creates a leak.   `isShowingProperty.dispose` is now called in `dialogDispose`. 

@jbphet said:
> my conclusion is that the dialogs are not leaking memory, they just take a while to allocate all that they use. 

I reviewed Dialog and I don't see any of the potential leak sources that existed when this issue created. So  I think we can close this issue... 

> There does seem to be a slow leak during fuzz testing, but when I compared the memory snapshots and spot checked a number of the additional allocations, they all seemed to be associated with Scenery pools. 

... and create an issue for Scenery pools.

**Comment by samreid** [comment]
I'm not opposed to further investigation, but the pattern we have seen previously in sims like graphing lines is that it takes 30+ minutes for our memory patterns to stabilize: https://github.com/phetsims/graphing-lines/issues/78#issuecomment-296837755.  So I'm not convinced that the data in https://github.com/phetsims/sun/issues/432#issuecomment-468052124 indicates a leak.  Happy to be proved otherwise, though!

**Comment by zepumph** [comment]
An idea of another test, manually set the Poolable option `maxSize` to 0, and see that there would be no slow "tail" increasing the memory as the pools get to their max size. 


this will be investigated in https://github.com/phetsims/phet-core/issues/55.

There seems to be no memory leak in Dialog. As of dev meeting today, closing
