### ISSUE TITLE
issues with RectangularButtonView radii options

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#454]
Noted in https://github.com/phetsims/sun/issues/448.

Rectangular has 4 corner-specific radii options that are undocumented, and appear only in `createButtonShape`. 

(1) Add something like this (untested) to the default options hash:

```js
// {number|null} corner-specific radii 
// If null, the option is ignore. 
// If non-null, it overrides cornerRadius for the associated corner of the button.
leftTopCornerRadius: null,
rightTopCornerRadius: null,
leftBottomCornerRadius: null,
rightBottomCornerRadius: null
```

(2) `createButtonShape` has a required argument named `options`.   Something like this would be preferable, where `radii` is cherry-picked from `options`.

```js
/**
 * @param {number} width
 * @param {number} height
 * @param {*} radii - values of radii-related options to RectangularButtonView's constructor
 */
  function createButtonShape( width, height, radii ) {
```

**Comment by pixelzoom** [comment]
In the above commits...

I address (1) as proposed above.   I punted on (2) and left `createButtonShape` alone, but documented and moved it after the constructor.  And I added an example to sun demo that demonstrates a button with corner-specific radii.

@jbphet please review.

**Comment by jbphet** [comment]
Seems fine to me.  I made a few additional changes:
+ Changed the `options` parameter to `config` in `createButtonShape`, since (as pointed out above) it is actually a required parameter
+ Added an output message for the "custom corner" button, since most if not all of the other buttons output a message
+ Cleaned up some comment documentation

@pixelzoom - I'm reasonably certain that you won't have any objection to the minor changes I've made, but feel free to review if you see this go by and are curious.  I'm going to go ahead and close it.
