### ISSUE TITLE
Allow slider track to be non-pickable

### ISSUE THREAD

**Issue by arnabp** [phetsims/sun#473]
@jbphet and I were looking at https://github.com/phetsims/blackbody-spectrum/issues/61 and realized the issue was due to the track, which was set to invisible in this sim, still being pickable. We've added an option to allow the track to be set to non-pickable.

**Comment by arnabp** [comment]
@pixelzoom does this seem like a reasonable solution and implementation?

**Comment by pixelzoom** [comment]
(1) Why is Slider involved for this? Are you saying that you're using a slider with no track in order to have a thumb move along the thermometer? My initial reaction is that this is a questionable use of a Slider.  Rather than adding more stuff to Slider, you should investigate an approach that doesn't involve Slider.  

(2) Where is this new `trackPickable` option used?  I don't see it in any commits here or in phetsims/blackbody-spectrum#61 that show it being used. 

(3) Are you certain that this is what was causing the problem? How is something that is invisible still receiving input events?

**Comment by pixelzoom** [comment]
I would expect the implementation of this to be similar to SCENERY_PHET/SpectrumSlider., which does not use a trackless Slider.

**Comment by pixelzoom** [comment]
> (3) Are you certain that this is what was causing the problem? How is something that is invisible still receiving input events?

The track is still visible, but has fill and stroke `'rgba( 0, 0, 0, 0 )'`.  That's not invisible, that's fully transparent (you could have also set `opacity:0`). 

If you really need to use a Slider, rather than resorting to specific fill and stroke, and having to create a new option, why not add the ability to hide the track?

**Comment by pixelzoom** [comment]
```js
/**
 * Sets visibility of the track.
 * @param {boolean} visible
 */
setTrackVisible( visible ) { 
  this.track.visible = visible; 
}
```

**Comment by pixelzoom** [comment]
BlackBodySpectrumScreenView:

```js
    var temperatureSlider = new VSlider( model.mainBody.temperatureProperty, temperatureRange, {
      trackSize: new Dimension2( 400, 5 ),
      thumbNode: triangleNode
    } );
    temperatureSlider.setTrackVisible( false );
```

**Comment by arnabp** [comment]
2) I'm still working on cleaning up some stuff in BlackBodySpectrumScreenView.js, I hadn't made the commit yet that included the trackPickable option, but...

I'll take a look at everything else you've said here now, including the SCENERY_PHET/SpectrumSlider implementation. At first glance, setTrackVisible looks like it'll suit this case better than pickable did.

**Comment by pixelzoom** [comment]
Here's another problem with using a Slider.  You're relying on magic numbers and "eyeballing" to get the Slider to line up with the thermometer.  These lines in BlackBodySpectrumScreenView.js are suspect:

```js
76 trackSize: new Dimension2( 400, 5 ),
166    temperatureSlider.left = blackbodySpectrumThermometer.right - 10;
167    temperatureSlider.centerY = blackbodySpectrumThermometer.centerY - 14;
```

**Comment by arnabp** [comment]
1) The initial implementation of this sim had a track and a slider together. Over time the track has disappeared, and the thumb has become more prominent. I was looking for a more simple way of having a disabled slider but like you mentioned, the approach that's currently being used has drifted too far away from the use of a slider.

3) "Invisible" was probably the wrong word here, as you noticed, I was referring to the track being transparent. 

I'm going to see about implementing the thumb without the slider at all, as Scenery_Phet/SpectrumSlider does. If that turns out to be an implementation that adds on way more code than it should, I'll go for the setTrackVisible approach.

Either way, the pickable code isn't necessary, so I'm going to go ahead and step that back.

**Comment by arnabp** [comment]
I've removed the slider from the thermometer, it now has its own implementation, no changes to Sun were needed, closing.
