### ISSUE TITLE
support Dialog.focusCloseButton() via a predicate option

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#539]
In a few places we have the following check when showing a Dialog:

```
    // if listener was fired because of accessibility
      if ( self.buttonModel.isA11yClicking() ) {

        // focus the close button if the dialog is open with a keyboard
        keyboardHelpDialog.focusCloseButton();
      }
```

What if that logic could be embedded in an option like:

`focusCloseButtonOnShowPredicate: ()=> this.buttonModel.isA11yClicking()`

That way this logic could be in Dialog.prototype.show, and could be used by every Dialog without added client side logic.

@jessegreenberg what do you think? I'm happy to implement if you like the idea.

**Comment by jessegreenberg** [comment]
All of the `self.buttonModel.isA11yClicking()` have been removed since this issue was created (also `isA11yClicking` function was renamed to `isPDOMClicking`) . PhET changed behavior so that focus always goes to the close button, regardless of the input method. Instead, the highlight is hidden depending on the input method. This issue can be closed.
