### ISSUE TITLE
Improve carousel support for items of different sizes

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#541]
When Circuit Construction Kit: DC was developed, Carousel did not have good support for showing items of different sizes.  Hence CCK uses a workaround where it sets the number of items per page in carousel to 1, and it lays out its own pages using `_.chunk`.  We previously discussed this problem and workaround in https://github.com/phetsims/circuit-construction-kit-dc/issues/91.  I wanted to discuss whether this workaround is still suitable for CCK AC publications, or if we should investigate integrating support for this directly into Carousel.

Tagging for potential work in https://github.com/phetsims/circuit-construction-kit-common/issues/528 and assigning to @ariel-phet for initial discussion.

**Comment by ariel-phet** [comment]
@samreid I think considering the extent of use of carousel in sims, and that we will likely be continuing to use this component in many future sims, it is worth the effort to not have a workaround, but rather improve the state of the code directly in Carousel.

**Comment by chrisklus** [comment]
>@samreid I think considering the extent of use of carousel in sims, and that we will likely be continuing to use this component in many future sims, it is worth the effort to not have a workaround, but rather improve the state of the code directly in Carousel.

+1, this is needed in Number Play as well.

**Comment by samreid** [comment]
@ariel-phet who would you recommend to work on this issue? @pixelzoom is the Carousel author and lead developer, and I don't have any significant experience with its implementation.  I'm happy to get up to speed, but it may be more efficient and effective for @pixelzoom to take the lead or provide guidance.

**Comment by pixelzoom** [comment]
Why isn't this just a matter of using AlignBox and AlignGroup to make all items in the Carousel have the same effective dimensions?

**Comment by samreid** [comment]
I just noticed https://github.com/phetsims/sun/issues/307 "Carousel should support objects of different sizes" which has a lot of discussion on this topic.  I'll take a look at AlignBox and AlignGroup and review that issue as well.

**Comment by pixelzoom** [comment]
I think it's necessary for each item in a Carousel to have the same effective size.  Otherwise how do we determine the size of the carousel, the size of a page, the number of items per page, ...

**Comment by samreid** [comment]
> Otherwise how do we determine the size of the carousel, the size of a page, the number of items per page, ...

For example, let's say I have items of sizes 4, 10, 3, 12, 8, 6, 7, 3 (in that order) and we specify that a carousel and its page are 30 units long.  Then 4, 10, 3, 12, fit on the first page and the rest fit on the second page.

**Comment by pixelzoom** [comment]
I don't agree with that direction.

**Comment by samreid** [comment]
Are you recommending that Carousel should not be able to support a use case like this?  If so, why?

![image](https://user-images.githubusercontent.com/679486/72440093-71482700-3765-11ea-9798-4d25c2b7faf1.png)

**Comment by pixelzoom** [comment]
This feels like a contrived example - you could scale the pencil down (as you did in CCK) and make the items the same size.  I'd like to see an example where that's not the case.

I see what you've done in CCK to make items appear to have different sizes.  To my eye, it looks cramped and lopsided - that's my subjective opinion.  

If you want to support layout of different-sized items as a (non default) option, go for it.  But I think the default should be the current behavior, possibly changing the implementation to use AlignBox and AlignGroup to accomplish that.

**Comment by samreid** [comment]
For the contrived case, I scaled the button to match the width of the coins, and it looked like this:

![image](https://user-images.githubusercontent.com/679486/72478303-e2f89300-37ae-11ea-905c-b5aa22520cb3.png)

It's not immediately clear to me that we would always be able to do that, or whether that would always be an acceptable design.

> I'd like to see an example where that's not the case.

Isn't that a question for our design team?

> I see what you've done in CCK to make items appear to have different sizes. To my eye, it looks cramped and lopsided - that's my subjective opinion.

In Circuit Construction Kit: DC, we applied a workaround with "pages" to go outside of the constraints afforded by Carousel, and it turned out like this:

![image](https://user-images.githubusercontent.com/679486/72479142-cf4e2c00-37b0-11ea-8fc5-a2acc3b24a33.png)

Are you saying that looks cramped and lopsided?  Or are you referring to CCK AC, which has not yet been fine tuned as part of https://github.com/phetsims/circuit-construction-kit-common/issues/507. For that issue, it will be nice to know whether we should operate under the constraint that all items should have the same effective size or not.

If you were implementing CCK: DC, would you have shrunk everything to the same height?  Or added bounding boxes around everything so they have different effective height?  How would that look compared to the screenshot above?

> If you want to support layout of different-sized items as a (non default) option, go for it.

I'm trying to understand your reasoning.  It sounds like you are saying some combination of the following:
* We don't need different sized items in carousels because it won't come up in practical designs 
* The implementation is simpler with same-sized items, so we should only support that
* The user experience is preferable with same-sized items, so we should require that.

I know that Function Builder specified items of the same size, and it works and looks great.  For Circuit Construction Kit, items have been different sizes and dimensions and we had to apply a workaround to get to a publishable point, see https://github.com/phetsims/sun/issues/307#issuecomment-317857763

I'd prefer we come to a team consensus for what's desired and the best strategy to get there.

In https://github.com/phetsims/sun/issues/307#issuecomment-317857763 @jonathanolson recommended that Carousel should gracefully support items of different dimensions.  It seems that way to me too, but I trust your judgment and that's why I'm taking time to try to understand your perspective.

**Comment by ariel-phet** [comment]
IMHO I think we will need the flexibility to support different sizes, but it does seem reasonable for the default to be the same size.

**Comment by pixelzoom** [comment]
> Are you saying that looks cramped and lopsided? Or are you referring to CCK AC, which has not yet been fine tuned

I was apparently looking at CCK:AC.  It never occurred to me that you hadn't done something general in ccl-common.

> I'm trying to understand your reasoning. It sounds like you are saying some combination of the following: ...

I'm saying that I haven't had a need to support different size items, and I was questioning that need because this will be a major change, and will add further complication to the implementation.   I was also questioning whether you're proposing new behavior or an option.

Based on @ariel-phet's input above, it sounds like there's a need to support both uniform (same item sizes) and nonuniform (different item sizes) layout.  So moving forward from that decision...

If you're proposing that this is the new behavior, and that clients who want uniform sizes are responsible for ensuring that, then I am pushing back.  In my experience, when items have slightly different widths (like dog.png, cat.png, and turtle.png in Equality Explorer) we still want them to be treated as if their widths are effectively equal.  And since that's been the typical case, I don't think we should have to deal with it in client (sim) code by (e.g.) having to wrap every item in an AlignBox. 

If you're proposing an option, then page layout should be factored out into 2 strategies:  uniform (the current implementation, simplified using AlignGroup and AlignBox), and nonuniform (what you've done in CCK:AC).  Perhaps you can refactor the CCK:AC code so that it can be used herein.  And I think that uniform layout should be the default.

**Comment by pixelzoom** [comment]
Looking at the currently implementation of Carousel...  We'll need to change more than layout in order to support pages that have different numbers of items. 

Examples:

* Options itemsPerPage, spacing, and margin all assume uniform item size and the same number of items per page. They are used to size the carousel and layout pages. They become irrelevant with non-uniform layout, and you'll need some way to specify carousel size.  You'll also need to decide how to compute spacing and margins. 

* Field `this.itemsPerPage` is irrelevant for non-uniform items.

* `scrollToItem`, `scrollToItemIndex`, `isItemVisible`, and `itemIndexToPageNumber` are all implemented based on the assumption that each page has the same number of items.   That's the majority of the public methods, and they will need to be reimplemented. 

... and there may be other things that I don't see immediately. 

None of this sounds easy or fun.

So.... Another option might be to take what you've done in CCK:AC, and generalize it as a subclass of Carousel ---  i.e., a subclass that sets `itemsPerPage: 1` and lays out its own pages using ` _.chunk`.   This would be much easier than changing Carousel.

**Comment by pixelzoom** [comment]
Above I suggested:
> Another option might be to take what you've done in CCK:AC, and generalize it as a subclass of Carousel ...

The more I chew on that suggestion, the less I like it.  It seems backwards.  Uniform items should be a special case of non-uniform items, not the other way around.  Addressing this issue correctly really seems like a complete rewrite of Carousel.

**Comment by samreid** [comment]
I also noticed that balancing act is using a variant of the carousel, called KitControlNode, which has layouts like this:

![image](https://user-images.githubusercontent.com/679486/72658839-f2750900-3973-11ea-8e5a-ee456f805095.png)

In that case, it makes sense to cluster all those nodes and the title as one Node, and then have the carousel show one Node per page--rather than try to accommodate this unusual layout in Carousel itself.

**Comment by samreid** [comment]
What if we change the interface for Carousel so that its constructor takes `Node[] pages` instead of `Node[] elements` + `options.itemsPerPage`?  Then we supplement that with any utilities necessary for creating nice carousel pages?  Then Carousel would only responsible for showing the pages and switching between them, not additionally responsible for laying out items within the pages.

**Comment by pixelzoom** [comment]
> I also noticed that balancing act is using a variant of the carousel, called KitControlNode, which has layouts like this:

I can't find `KitControlNode`.  I see `KitCollectionNode` in build-a-molecule, but nothing with a similar name in balancing-act.   In any case, this layout is problematic for reasons other than the grid nature of the page that you've shown in the above screen shot.  Each page has its own layout (some grid, some not), and each page has a title (e.g. "People").  This is a big deviation from Carousel.

> What if we change the interface for Carousel so that its constructor takes `Node[]` pages ...

Once again, I feel like we're going down the path of trying to support too many options, instead of examining the designs and asking "do we really need (and can we afford) those options?"   This "feature creep" has happened (and continued to happen) with numerous PhET UI components -- NumberControl, Slider, ...  That said...

As a client, I really don't want to be responsible for creating pages.  And it makes it problematic to implement  `scrollToItem`, `scrollToItemIndex`, `isItemVisible`, and `itemIndexToPageNumber` -- if pages are `{Node[]}`, then they are opaque, how do you proposed to implement those methods?  Even with utilities for creating common page layouts, we will end up with different implementations of "page" -- isn't that also a problem?

Finally, I also don't see how this would be a big savings over having multiple page layout strategies as an option to Carousel, e.g.:

```js
// Equality Explorer
new Carousel( ..., {
  pageLayoutStrategy: Carousel.UNIFORM_ITEMS_PAGE_LAYOUT_STRATEGY
} );

// CCK:DC
new Carousel( ..., {
  pageLayoutStrategy: Carousel.NON_UNIFORM_PAGE_LAYOUT_STRATEGY
} );

// Balancing Act
new Carousel( ..., {
  pageLayoutStrategy: BAACarouselPageLayoutStrategy
} );
```

**Comment by samreid** [comment]
> I can't find KitControlNode. 

It was deleted 4 days ago in https://github.com/phetsims/balancing-act/issues/97.  It predated Carousel and had around 400 lines of code to provide similar functionality.

> Each page has its own layout (some grid, some not), and each page has a title (e.g. "People"). This is a big deviation from Carousel.

Yes, I agree Carousel currently does not support page titles.  But if it takes `Node[] pages` then it wouldn't need to.

> Once again, I feel like we're going down the path of trying to support too many options, instead of examining the designs and asking "do we really need (and can we afford) those options?

Changing Carousel's responsibility to be about pages rather than nodes is a simplifying step, not a complicating step.  Does Carousel really need to know about the layout/spacing/grouping of individual nodes?  Why should that be Carousel's responsibility?

> As a client, I really don't want to be responsible for creating pages.

We could provide an interface like so:

```js
new Carousel({
   pages: Carousel.createPages(nodes,{nodesPerPage: 4});
})
```

Then this layout logic will separated and easier to isolate/test/improve rather than buried halfway through Carousel.  It is very much like the layout strategies you proposed, but a little more flexible.

> And it makes it problematic to implement  `scrollToItem`, `scrollToItemIndex`, `isItemVisible`, and `itemIndexToPageNumber` 

The function `isItemVisible` is currently unused across our project.  The other 3 methods only appear to be used in SceneNode's `getCarouselPosition` for `populateFunctionCarousels` and `populateCardCarousels` to compute the location to pop out the nodes.  But it looks like this implementation of `carouselPosition = ...` is unnecessary--a simpler implementation would be to use localToGlobal/globalToParent for getting their "pop out" positions when the icon is pressed.

> Finally, I also don't see how this would be a big savings over having multiple page layout strategies as an option to Carousel, e.g.:

It's a simplifying step.  `Nodes` + `Layout` = `Pages`.  It seems more general to just provide `Pages` and let the client determine how to create them, rather than passing a function that takes nodes and returns the pages, and then also passing in the nodes.

**Comment by samreid** [comment]
`Carousel` already supports as page-oriented API, if you specify `itemsPerPage: 1`.  That's the strategy used in Circuit Construction Kit and now Balancing Act.

**Comment by ariel-phet** [comment]
We likely need a design discussion for carousel - it might require a bit of a rewrite to support various goals. Marking for design meeting and referencing https://github.com/phetsims/balancing-act/issues/97 again.

**Comment by samreid** [comment]
SR: Should we retain the current ability of carousel to deal with `items[]` and the "hack" of `itemsPerPage: 1`?
It seems we will need the ability to do custom layouts in some cases.

SR: Should we investigate a strategy where the layout code is factored out to a separate function, and can be re-run when necessary?
CM: That sounds like it's worth investigation.
KP: It's nice because we could opt-in one component at a time without having to do everything.
KP: SR, go ahead and give it a try, perhaps in ComboBox.
KP: We will eventually want to do this for Carousel as well.

Q: Should Carousel have an PhET-iO API for hiding entire pages?
A: Probably at some point.

Q: Should Carousel support items of different sizes?
A: It already does, see expression exchange.

KP: Let's leave the "hack" strategy for now, and see how the relayout strategy works out.
SR: It's not clear that making icons invisible would automatically reflow the layout.  Should we have a different facet for determining the layout, or should the visibility determine it?

KP: Should there be a button in studio that runs the relayout?  So you can control where the holes appear?
SR: It seems better to reflow automatically.

**Comment by samreid** [comment]
I'll pursue the more general layout idea in https://github.com/phetsims/joist/issues/608

**Comment by samreid** [comment]
https://github.com/phetsims/joist/issues/608 is closed, we can see how well it works for this issue.

**Comment by samreid** [comment]
The CCK dc carousel pages are implemented via VBox, so it was trivial to make it automatically adjust layout.  I did so in the commit.

![Kapture 2020-11-02 at 11 41 23](https://user-images.githubusercontent.com/679486/97906438-e4c12200-1d00-11eb-9a9b-5f4d2750f9bd.gif)

Can this issue be closed?

**Comment by pixelzoom** [comment]
I have no idea. I haven't been following this issue, and I don't have time to read through all of the comments to determine how this was addressed.

**Comment by samreid** [comment]
@ariel-phet where would you like to go with this issue?

**Comment by pixelzoom** [comment]
To clarify... If someone wants to summarize how this issue was addressed, I'll be happy to review.  I see that LayoutBox option `excludeInvisibleChildrenFromBounds` is somehow involved.  But it's not clear to me how Carousel features that assume the same number of items per page (e.g. `itemsPerPage`, `spacing`, `scrollToItem`, `scrollToItemIndex`) are being supported.  Are you still using the "hack" or setting `itemsPerPage: 1` and requiring the client to combine multiple items into 1 item?

**Comment by samreid** [comment]
Yes, we are still using the "hack" of `itemsPerPage: 1` as prescribed in https://github.com/phetsims/sun/issues/541#issuecomment-586002421 to allow clients to form their own pages.

**Comment by pixelzoom** [comment]
So let me see if I can summarize:

* The title of this issue is "Improve carousel support for items of different sizes".
* We did not add any such support to carousel.
* If a client wants different-sized items, and/or different number of items per page, then they must (1) set `itemsPerPage: 1` and (2) create their own composite "items" that handle the custom layout of their actual items.

If that's correct and acceptable to everyone, I'm OK with closing this issue.

**Comment by samreid** [comment]
That sounds reasonable to me.

**Comment by ariel-phet** [comment]
I agree we can go ahead and close.
