### ISSUE TITLE
Option to change Carousel arrow button sounds

### ISSUE THREAD

**Issue by Denz1994** [phetsims/sun#547]
Found during https://github.com/phetsims/build-a-molecule/issues/108 and related phetsims/tambo#73.

Carousel buttons by default produce sound when clicked. The suggestion is to expose an option to disable or change this sound. This would look something like what was done to other common code buttons.

**Comment by Denz1994** [comment]
@jbphet Could you review this change to Carousel and close if all looks good?

**Comment by jbphet** [comment]
Thanks for doing this @Denz1994.  One suggestion: I would recommend naming the option `buttonSoundPlayer` instead of `soundPlayer` to be consistent with other button-specifiec options, and also because we may in the future want to add a specific `soundPlayer` option for the carousel motion itself.  If you concur, feel free to implement and close.

**Comment by Denz1994** [comment]
Thanks for the input @jbphet. `soundPlayer` has been changed to `buttonSoundPlayer` in the above commits. Closing this issue.
