### ISSUE TITLE
pattern for calling addLinkedElement

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#551]
Related to https://github.com/phetsims/tasks/issues/1017 and https://github.com/phetsims/sun/issues/420.

This TODO was added to ComboBox by @zepumph:

```js
      // TODO should this be graceful?
      property.isPhetioInstrumented() && this.addLinkedElement( property, {
        tandem: options.tandem.createTandem( 'property' )
      } );
```

Should this same pattern be used in other common code where `addLinkedElement` is called?

**Comment by zepumph** [comment]
@samreid over in `Checkbox` it looks like we are always adding the linked Property (if the option is true), should we do the same pattern here?

**Comment by samreid** [comment]
In the commits, we removed an older, unused pattern for opting out of addLinkedElement, and we made it so uninstrumented targets are not linked.  We will need to be more vigilant in design meetings, since we will no longer have an error message if we create, say, a UI component with an uninstrumented Property.  I added a PSA for the next team PhET-iO design meeting.

Sliders have a way to pass an alternate property to link.  Closing.

**Comment by zepumph** [comment]
@samreid can you please let me know what you are thinking for this issue? Should I be assigned?

**Comment by samreid** [comment]
From Thursday team meeting:

> PSA: From https://github.com/phetsims/sun/issues/551 Previously, uninstrumented elements caused an error when trying to create a linked element.  Now that is an acceptable use case.  We will need to be more vigilant in design meetings, since we will no longer have an error message if we create, say, a UI component with an uninstrumented Property. Perhaps design teams already have a good eye for looking for these linked elements and correctly instrumented model properties, so we don’t need that extra check.

@ariel-phet said:

> Can we run a report that displays all of the things that we thought maybe should be instrumented but weren’t instrumented?

@pixelzoom said:
> What we really need is a mode where we can run studio with a partial instrumentation.  
> Use something like options.phetioLinkProperty so we can opt out explicitly, then the client can create the linked element as necessary.  But the code should be automatically checking that things are instrumented in the default case.

**Comment by samreid** [comment]
Maybe one step would be to add back checks here, but skip them when `&phetioValidateTandems` is off.  See notes in https://github.com/phetsims/phet-io/issues/1605

**Comment by pixelzoom** [comment]
Yes, that was suggested in 1/16/20 phet-io meeting.   But validating a link is not the same as validating a tandem.  Would you change the name of `phetioValidateTandems`?

**Comment by pixelzoom** [comment]
`phetioValidate` ?

**Comment by samreid** [comment]
Since the previous comment, we have replaced the `phetioValidateAPI` query parameter with `phetioReferenceAPI` and `phetioReferenceAPIValidationLevel`, so we could expand `phetioValidateTandems` to be more general without much confusion.  But I didn't fully understand the proposal from this issue:

> Use something like options.phetioLinkProperty so we can opt out explicitly, then the client can create the linked element as necessary. 

@pixelzoom are you saying that clients would put `phetioLinkProperty: false` during development, then later specify `phetioLinkProperty: true` when it is getting closer to production?  How will we remember to turn that on?  What is your current recommendation for this issue?

**Comment by pixelzoom** [comment]
I honestly don't recall providing that feedback (that was almost 5 months ago). So sorry, I don't know what "Use something like options.phetioLinkProperty" means.

**Comment by zepumph** [comment]
Over in https://github.com/phetsims/joist/issues/654 I desire `phetioLinkProperty` as an option because the subclassing of Checkbox means that currently we end up with the linked property as a sibling to the LinkedElement:
![image](https://user-images.githubusercontent.com/6856943/90829201-cb0c6300-e2eb-11ea-893c-333c34ed76c6.png)


This is a case that doesn't apply to iterative development, but in fact is just a spot where it makes sense to opt out of the linking. Let me know if that is problematic!

**Comment by zepumph** [comment]
I removed the only usages of a isInstrumented check before adding a linked element.
