### ISSUE TITLE
ABSwitch phetioFeatured defaults

### ISSUE THREAD

**Issue by arouinfar** [phetsims/sun#572]
In https://github.com/phetsims/ph-scale/issues/117 @kathy-phet and I reviewed the ABSwitch, and decided on the general pattern for what should be featured.

ABSwitch.visibleProperty
ABSwitch.AText.textProperty
ABSwitch.AText.visibleProperty
ABSwitch.BText.textProperty
ABSwitch.BText.visibleProperty
ABSwtich.toggleSwitch.visibleProperty

Assigning to the PhET-iO team.

**Comment by zepumph** [comment]
>ABSwtich.toggleSwitch.visibleProperty
ABSwitch.visibleProperty

Implemented above. These were easy because we create these in `ABSwitch`

>ABSwitch.AText.textProperty
ABSwitch.AText.visibleProperty
ABSwitch.BText.textProperty
ABSwitch.BText.visibleProperty

This is going to be much more difficult, because these use "dependency injection" such that they are created, and then passed to ABSwitch. Things to note. ABSwitch allows these to be any Node, it is only ph-scale specifically that is passing texts in. Thus likely you should set the textProperties in the overrides (or put them in ph-scale code). 

The best we can do for the visibileProperty features is assert that they are featured when passed into ABSwitch, but it will still be on the client of ABSwitch to implement. Do you think that is preferrable to designers supplying each time in the overrides?

**Comment by arouinfar** [comment]
>>ABSwtich.toggleSwitch.visibleProperty
ABSwitch.visibleProperty
>
>Implemented above. These were easy because we create these in ABSwitch

👍 

>>ABSwitch.AText.textProperty
ABSwitch.AText.visibleProperty
ABSwitch.BText.textProperty
ABSwitch.BText.visibleProperty
>
>This is going to be much more difficult, because these use "dependency injection" such that they are created, and then passed to ABSwitch. Things to note. ABSwitch allows these to be any Node, it is only ph-scale specifically that is passing texts in. Thus likely you should set the textProperties in the overrides (or put them in ph-scale code).
>
>The best we can do for the visibileProperty features is assert that they are featured when passed into ABSwitch, but it will still be on the client of ABSwitch to implement. Do you think that is preferrable to designers supplying each time in the overrides?

Thanks for the clarification @zepumph! I think it would be best to handle these in the overrides, since it isn't a general pattern for all ABSwitches. 

I don't think there's anything else that needs to be done for this issue, so I'll go ahead and close.
