### ISSUE TITLE
Decrease the opacity of disabled components

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#578]
From https://github.com/phetsims/gravity-and-orbits/issues/294#issuecomment-600735987, @kathy-phet said:

- [ ] Making Enbled=false dims the controls a lot, making them hard to see. It looks like it it is setting things to about 30% opacity. We would recommend 50%. Can you look at the defaults here? 
![image](https://user-images.githubusercontent.com/5096804/76984137-0dc4ac00-6904-11ea-8b8c-bf8d06d5d157.png)

**Comment by samreid** [comment]
Changed in the commit.  I tested this in both concentration (white background) and gravity and orbits (black background) and it seemed reasonable to me.  Still, this change will appear in all or nearly all of our sims, so I think it should be carefully reviewed before publication.  Blocking until then.  @pixelzoom or @zepumph can you please review the implementation side?  Are there any components not using this constant, that should use it?  @arouinfar or @kathy-phet or @ariel-phet can you please review the design side?  Any qualms about applying this across the project?

**Comment by pixelzoom** [comment]
I have qualms about applying this across the project.  This affects many common-code and sim-specific UI components.  The only reason it doesn't affect _all_ of them is because it's not being used in every place that it should be.  And that's certainly going to change when `EnabledComponent` mixin gets integrated to support `enbledProperty` across the project, see https://github.com/phetsims/sun/issues/257#issuecomment-600964209.  I recall that we also chose `SunConstants.DISABLED_PROPERTY: 0.3` after careful consideration, not arbitrarily.

**Comment by pixelzoom** [comment]
I also think that evaluating this on a black background what's causing you to use a higher opacity value.

**Comment by pixelzoom** [comment]
I have qualms about applying this across the project.  This affects many common-code and sim-specific UI components.  The only reason it doesn't affect _all_ of them is because it's not being used in every place that it should be.  And that's certainly going to change when `EnabledComponent` mixin gets integrated to support `enbledProperty` across the project, see https://github.com/phetsims/sun/issues/257#issuecomment-600964209.  I recall that we also chose `SunConstants.DISABLED_PROPERTY: 0.3` after careful consideration, not arbitrarily.

I also think that evaluating this on a black background is what's causing you to use a higher opacity value.   

I recommend:
* Set the default based on a light background.
* Support changing the default in `EnabledComponent` via `options.disabledOpacity`.
* Use `EnabledComponent` wherever `enabledProperty` is needed.

**Comment by samreid** [comment]
Here is opacity 0.3 (top) and opacity 0.5 (bottom) for Concentration.  I believe our lives will be simpler if we can choose a value that works well by default on many backgrounds, if possible.  Maybe 0.4 or so is a good compromise?  But I agree we often also want the ability to fine-tune beyond the defaults:

![image](https://user-images.githubusercontent.com/679486/77028933-e8fe2200-695f-11ea-9620-9f29d5f02ffe.png)

**Comment by pixelzoom** [comment]
> I believe our lives will be simpler if we can choose a value that works well by default on many backgrounds, if possible. 

I believe that was our conclusion when we chose 0.3 as the default. See https://github.com/phetsims/sun/issues/171#issuecomment-94833804 and https://github.com/phetsims/sun/commit/1068a9802ddfe4f267c551ef0de17a192b0252a7.

**Comment by pixelzoom** [comment]
See also https://github.com/phetsims/sun/issues/489, where `SunConstants.DISABLED_OPACITY: 0.3` was used throughout the project.  The value `0.3` was widely used, and was simply consolidated into a constant.   

I'm not saying that we shouldn't change it if it's indeed an improvement.  But I am questioning the context in which we're making that decision, and wondering why 0.3 has been OK for so long.

**Comment by pixelzoom** [comment]
Note that 0.3 is still hard-coded in sun buttons.

```js
// RectangularButtonView.js
      content.opacity = state === ButtonInteractionState.DISABLED ||
                        state === ButtonInteractionState.DISABLED_PRESSED ? 0.3 : 1;

// RoundButtonView.js
      content.opacity = state === ButtonInteractionState.DISABLED ||
                        state === ButtonInteractionState.DISABLED_PRESSED ? 0.3 : 1;
```

**Comment by kathy-phet** [comment]
As I have been testing in Studio over the past few months, the disabled opacity has been feeling consistently too transparent. I agree we should have a meeting of designers to discuss and look across components, but at this time, I would lean to a default closer to 0.5 across all components and backgrounds.

**Comment by zepumph** [comment]
I agree with @pixelzoom that the default should first be decided based on light backgrounds. It sounds like another design meeting for this would be good. I am skeptical that we will be able to find an opacity with good enough contrast for all backgrounds, but it would be very pleasant if that happens.

**Comment by mattpen** [comment]
Dev Meeting 3/19: We'll revert to 0.3 opacity so this doesn't block publication, then experiment further with the design team.  

@samreid is going to revert it.

**Comment by arouinfar** [comment]
A few thoughts here...
* The opacity of disabled UI components hasn't gotten much notice from designers because sims rarely have that many disabled components (if any at all). As PhET-iO work ramps up and we spend lots of time in studio, the opacity of disabled components is something we've attended to more, especially because many components have their `enabledProperty` featured.
* Consistency is preferable. I'm generally of the opinion that we should be using the same opacity for all disabled UI components. Perhaps @samreid's suggestion of 0.4 would be a happy medium.
* While I appreciate that 0.3 was not an arbitrary choice, it was made when there were far fewer HTML5 sims (20), and only one of those had a black background (Color Vision).

**Comment by pixelzoom** [comment]
Thinking about this more...  We should choose an opacity that works well on both light and dark backgrounds.  Otherwise we're liable to end up with a bunch of different (inconsistent) opacities on dark backgrounds.  If we can't come up with such an opacity, let's create a new constant like `SunConstants.DISABLED_OPACITY_DARK_BACKGROUND` and use that where needed, instead of hard-coding opacity values.

**Comment by kathy-phet** [comment]
On the plus side, PhET-iO makes is really easy to try out lots of conditions now.

**Comment by samreid** [comment]
@arouinfar are you set up so that you can change the value in sun/js/SunConstants.js in your working copy, and test it in a variety of different simulations and recommend a value that will work in the majority of cases?  Would that be a good way to proceed?

**Comment by arouinfar** [comment]
Since there aren't many sims with disabled components, I decided to make the changes to `opacityProperty` in studio to simulate different alpha levels for `enabledProperty`.  

Here's a side-by-side comparison of various UI components on different backgrounds. If the images look small on your screen, I suggest clicking on them to open in a new tab. I generally  think an opacity of 0.3 is too low. An opacity of 0.5 looks sufficiently disabled to me, but I think anything [0.4, 0.5] could work.

@kathy-phet @ariel-phet thoughts?

| 0.3 | 0.4 | 0.5 | 1.0 | 
| --- | --- | --- | --- | 
| ![image](https://user-images.githubusercontent.com/8419308/77195171-d3dfdb00-6aa6-11ea-966c-b525c98cd427.png) | ![image](https://user-images.githubusercontent.com/8419308/77195115-bad72a00-6aa6-11ea-911c-0a98c66484a1.png) | ![image](https://user-images.githubusercontent.com/8419308/77195082-ab57e100-6aa6-11ea-8ffa-7fe5b4d9f4b6.png) | ![image](https://user-images.githubusercontent.com/8419308/77195044-9bd89800-6aa6-11ea-8795-8ff17d164742.png) |
| ![image](https://user-images.githubusercontent.com/8419308/77200273-db57b200-6aaf-11ea-8ec7-1aa52df30c9f.png) | ![image](https://user-images.githubusercontent.com/8419308/77200241-cc70ff80-6aaf-11ea-8c51-611b2f458e4b.png) | ![image](https://user-images.githubusercontent.com/8419308/77200210-b8c59900-6aaf-11ea-9421-6430d85c468f.png) | ![image](https://user-images.githubusercontent.com/8419308/77200226-c0853d80-6aaf-11ea-810b-c8850338ed62.png) | 
| ![image](https://user-images.githubusercontent.com/8419308/77200749-d6dfc900-6ab0-11ea-82f4-fa2a9380e92a.png) | ![image](https://user-images.githubusercontent.com/8419308/77200729-caf40700-6ab0-11ea-862d-73af371f26c8.png) | ![image](https://user-images.githubusercontent.com/8419308/77200699-badc2780-6ab0-11ea-846b-d487c5016b1b.png) | ![image](https://user-images.githubusercontent.com/8419308/77200675-ab5cde80-6ab0-11ea-901a-38337f611c66.png) |
| ![image](https://user-images.githubusercontent.com/8419308/77200992-4fdf2080-6ab1-11ea-95b6-a65cca737e11.png) | ![image](https://user-images.githubusercontent.com/8419308/77200976-46ee4f00-6ab1-11ea-9072-72a93e329a95.png) | ![image](https://user-images.githubusercontent.com/8419308/77200945-3ccc5080-6ab1-11ea-8903-b482fb195cc4.png) | ![image](https://user-images.githubusercontent.com/8419308/77200929-32aa5200-6ab1-11ea-850b-c457e023040f.png) |
| ![image](https://user-images.githubusercontent.com/8419308/77201461-22df3d80-6ab2-11ea-843e-aab858973859.png) | ![image](https://user-images.githubusercontent.com/8419308/77201448-19ee6c00-6ab2-11ea-9741-918240f9b01b.png) | ![image](https://user-images.githubusercontent.com/8419308/77201422-10fd9a80-6ab2-11ea-9cad-2ca5d6808344.png) | ![image](https://user-images.githubusercontent.com/8419308/77201388-06430580-6ab2-11ea-9f35-62ad35abff08.png) |
| ![image](https://user-images.githubusercontent.com/8419308/77201638-6e91e700-6ab2-11ea-82aa-e1263433ed66.png) | ![image](https://user-images.githubusercontent.com/8419308/77201670-7d789980-6ab2-11ea-8df0-0b836c4fdf1b.png) | ![image](https://user-images.githubusercontent.com/8419308/77201684-87020180-6ab2-11ea-904b-9e235bedb230.png) | ![image](https://user-images.githubusercontent.com/8419308/77201611-63d75200-6ab2-11ea-90c7-c3ef628f937e.png) |
| ![image](https://user-images.githubusercontent.com/8419308/77202154-64241d00-6ab3-11ea-92c7-5664b4a63366.png) | ![image](https://user-images.githubusercontent.com/8419308/77201985-1b6c6400-6ab3-11ea-9768-fba687f03e8b.png) | ![image](https://user-images.githubusercontent.com/8419308/77201886-ef50e300-6ab2-11ea-95cb-775e6f31b61d.png) | ![image](https://user-images.githubusercontent.com/8419308/77201843-da744f80-6ab2-11ea-94bd-1712572379b7.png) |
| ![image](https://user-images.githubusercontent.com/8419308/77202524-21af1000-6ab4-11ea-9f8e-4ad4d5a36db4.png) | ![image](https://user-images.githubusercontent.com/8419308/77202497-19ef6b80-6ab4-11ea-8b95-9afb6bbb16c5.png) | ![image](https://user-images.githubusercontent.com/8419308/77202474-0e03a980-6ab4-11ea-865c-62393b24b59f.png) | ![image](https://user-images.githubusercontent.com/8419308/77202450-ffb58d80-6ab3-11ea-899a-6b9c41380331.png) |
| ![image](https://user-images.githubusercontent.com/8419308/77203020-16101900-6ab5-11ea-91d0-0991c2727c36.png) | ![image](https://user-images.githubusercontent.com/8419308/77202998-07c1fd00-6ab5-11ea-8d55-1d0e9e5f3bd0.png) | ![image](https://user-images.githubusercontent.com/8419308/77202967-f5e05a00-6ab4-11ea-9035-a37a8de334d8.png) | ![image](https://user-images.githubusercontent.com/8419308/77202929-e3662080-6ab4-11ea-852f-8eb04fa1d6c3.png) |
| ![image](https://user-images.githubusercontent.com/8419308/77203891-2d500600-6ab7-11ea-9681-82e8716c08b2.png) | ![image](https://user-images.githubusercontent.com/8419308/77203863-1dd0bd00-6ab7-11ea-9e61-d135681176f6.png) | ![image](https://user-images.githubusercontent.com/8419308/77203833-0d204700-6ab7-11ea-9815-a95c6de31d5a.png) | ![image](https://user-images.githubusercontent.com/8419308/77203179-6b4c2a80-6ab5-11ea-9926-cb44a102f299.png) |
| ![image](https://user-images.githubusercontent.com/8419308/77204097-a0597c80-6ab7-11ea-877e-34192460fcd3.png) | ![image](https://user-images.githubusercontent.com/8419308/77204059-8cae1600-6ab7-11ea-83cf-cd64f79caef6.png) | ![image](https://user-images.githubusercontent.com/8419308/77204023-786a1900-6ab7-11ea-90d3-bccbf48a8fc9.png) | ![image](https://user-images.githubusercontent.com/8419308/77203984-62f4ef00-6ab7-11ea-96c5-1dacd0bdf02b.png) |
| ![image](https://user-images.githubusercontent.com/8419308/77204808-21fdda00-6ab9-11ea-9590-dc162fd47376.png) | ![image](https://user-images.githubusercontent.com/8419308/77204778-16121800-6ab9-11ea-8c27-8781e0158e08.png) | ![image](https://user-images.githubusercontent.com/8419308/77204557-984e0c80-6ab8-11ea-9042-2ae775f1d385.png) | ![image](https://user-images.githubusercontent.com/8419308/77204262-f4fcf780-6ab7-11ea-97a5-a7618d0a8870.png) |
| ![image](https://user-images.githubusercontent.com/8419308/77205515-a56bfb00-6aba-11ea-8eb9-519c318d2d9f.png) | ![image](https://user-images.githubusercontent.com/8419308/77205458-840b0f00-6aba-11ea-83cb-dc1b9a80244d.png) | ![image](https://user-images.githubusercontent.com/8419308/77205393-6342b980-6aba-11ea-939d-013776d6c9d5.png) | ![image](https://user-images.githubusercontent.com/8419308/77205311-3a222900-6aba-11ea-9df1-edfebb6046d4.png) |
| ![image](https://user-images.githubusercontent.com/8419308/77206008-a81b2000-6abb-11ea-87a3-a6ab0fb814f3.png) | ![image](https://user-images.githubusercontent.com/8419308/77205963-99346d80-6abb-11ea-8d36-e99714d07da9.png) | ![image](https://user-images.githubusercontent.com/8419308/77205929-86219d80-6abb-11ea-807a-f2a378a3c043.png) | ![image](https://user-images.githubusercontent.com/8419308/77205914-7a35db80-6abb-11ea-9172-782db8bc147b.png) |
| ![image](https://user-images.githubusercontent.com/8419308/77206444-9a19cf00-6abc-11ea-9ae9-03f44541b81a.png) | ![image](https://user-images.githubusercontent.com/8419308/77206424-8c644980-6abc-11ea-93f5-6e9536f1e918.png) | ![image](https://user-images.githubusercontent.com/8419308/77206411-840c0e80-6abc-11ea-921e-42bfeabf5b04.png) | ![image](https://user-images.githubusercontent.com/8419308/77206360-62ab2280-6abc-11ea-8882-851c7f4132d4.png) |
| ![image](https://user-images.githubusercontent.com/8419308/77206771-68edce80-6abd-11ea-8870-5c5f0ca2e370.png) | ![image](https://user-images.githubusercontent.com/8419308/77206736-4bb90000-6abd-11ea-8932-eeb6f2079d34.png) | ![image](https://user-images.githubusercontent.com/8419308/77206719-40fe6b00-6abd-11ea-9f90-da13132f0cd3.png) | ![image](https://user-images.githubusercontent.com/8419308/77206702-33e17c00-6abd-11ea-8740-3efe711d87b4.png) |

**Comment by kathy-phet** [comment]
Thanks, Amy. I favor the 0.5 one myself.

**Comment by ariel-phet** [comment]
@arouinfar @kathy-phet I would go with 0.4 personally.

Although I agree in that in many of the cases the 0.5 would probably be sufficient, when there are bright colors on a background, it is less obvious to me. For instance in the case of the speed graph in gas properties (and to a lesser extent the multiple check boxes in natural selection), 0.5 feels a bit ambiguous to me. 

So I would strongly favor 0.4, as it does not feel too dark on a black background to me.

**Comment by arouinfar** [comment]
Thanks for the feedback @ariel-phet @kathy-phet. I have a slight preference for 0.4 over 0.5, but I think it would be good for @amanda-phet to also chime in here since this is a change affecting all sims.

@amanda-phet can you take a look at https://github.com/phetsims/sun/issues/578#issuecomment-601916312? Currently, setting `enabledProperty` to false sets the opacity of the UI component to 0.3 which we're finding to be too low and would like to increase it. What opacity do you most prefer?

**Comment by amanda-phet** [comment]
I reviewed this issue to catch up and took a close look at many of the examples (thanks for creating all of those). For sims with a black background, 0.5 seems the best, but for colored backgrounds, 0.4 seems better to me. The annoying thing about using opacity is that in any case other than a white background the component can look really muddy, so I understand why 0.5 seems preferable to some. However, 0.4 looks more certainly disabled in those cases. So 0.4 would be my preference.

**Comment by kathy-phet** [comment]
We should have a in-person meeting to discuss it. Even on white, the 0.5 looks quite disabled to me compared to the 1.0. The 0.4 gets quite challenging for me to read.

**Comment by arouinfar** [comment]
Thanks @amanda-phet! 

@kathy-phet agreed that it would be good to discuss as a team. I've set up a reminder to request time for this at next week's design meeting.

**Comment by kathy-phet** [comment]
@arouinfar - Can you make a middle of the road - 0.45 version?

**Comment by arouinfar** [comment]
Will do @kathy-phet.

**Comment by pixelzoom** [comment]
Strongly recommended to choose a value that works on all background.  If we decide to use different opacity for different backgrounds (light vs dark), it's going to be a significant cost in the long run.

**Comment by pixelzoom** [comment]
I'm going to abstain from a offering an opinion on which opacity value is best.  But I strongly recommended choosing a single default value for use on all background (with an option to change the default that is rarely used).  If we decide to use different opacity for different backgrounds (light vs dark), it's going to be a significant cost in the long run.  So if it comes down to a compromise, I think that choosing a single value is worth that compromise.

**Comment by arouinfar** [comment]
@pixelzoom I believe we're all on board with choosing a single default value. The only remaining question is what that value will be.

Here's an updated table which includes 0.45 for today's design meeting.

| 0.4 | 0.45 | 0.5 |
| --- | --- | --- | 
| ![image](https://user-images.githubusercontent.com/8419308/77195115-bad72a00-6aa6-11ea-911c-0a98c66484a1.png) | ![image](https://user-images.githubusercontent.com/8419308/78919177-c935b780-7a4e-11ea-91ca-a02c63602ac7.png) | ![image](https://user-images.githubusercontent.com/8419308/77195082-ab57e100-6aa6-11ea-8ffa-7fe5b4d9f4b6.png) | 
| ![image](https://user-images.githubusercontent.com/8419308/77200241-cc70ff80-6aaf-11ea-8c51-611b2f458e4b.png) | ![image](https://user-images.githubusercontent.com/8419308/78919445-25004080-7a4f-11ea-8117-658ab1ec9a4c.png) | ![image](https://user-images.githubusercontent.com/8419308/77200210-b8c59900-6aaf-11ea-9421-6430d85c468f.png) | 
| ![image](https://user-images.githubusercontent.com/8419308/77200729-caf40700-6ab0-11ea-862d-73af371f26c8.png) | ![image](https://user-images.githubusercontent.com/8419308/78919548-4b25e080-7a4f-11ea-939f-54c96abe2664.png) | ![image](https://user-images.githubusercontent.com/8419308/77200699-badc2780-6ab0-11ea-846b-d487c5016b1b.png) | 
|  ![image](https://user-images.githubusercontent.com/8419308/77200976-46ee4f00-6ab1-11ea-9072-72a93e329a95.png) | ![image](https://user-images.githubusercontent.com/8419308/78919629-6c86cc80-7a4f-11ea-8422-9ebae398ee8a.png) | ![image](https://user-images.githubusercontent.com/8419308/77200945-3ccc5080-6ab1-11ea-8903-b482fb195cc4.png) | 
| ![image](https://user-images.githubusercontent.com/8419308/77201448-19ee6c00-6ab2-11ea-9741-918240f9b01b.png) | ![image](https://user-images.githubusercontent.com/8419308/78919735-93dd9980-7a4f-11ea-9c27-4142214fdb11.png) | ![image](https://user-images.githubusercontent.com/8419308/77201422-10fd9a80-6ab2-11ea-9cad-2ca5d6808344.png) | 
| ![image](https://user-images.githubusercontent.com/8419308/77201670-7d789980-6ab2-11ea-8df0-0b836c4fdf1b.png) | ![image](https://user-images.githubusercontent.com/8419308/78920162-372eae80-7a50-11ea-8896-eaef6b6b2bfc.png) | ![image](https://user-images.githubusercontent.com/8419308/77201684-87020180-6ab2-11ea-904b-9e235bedb230.png) | 
| ![image](https://user-images.githubusercontent.com/8419308/77201985-1b6c6400-6ab3-11ea-9768-fba687f03e8b.png) | ![image](https://user-images.githubusercontent.com/8419308/78928295-93e49600-7a5d-11ea-9ab5-4d4019d9c2cb.png) | ![image](https://user-images.githubusercontent.com/8419308/77201886-ef50e300-6ab2-11ea-95cb-775e6f31b61d.png) | 
| ![image](https://user-images.githubusercontent.com/8419308/77202497-19ef6b80-6ab4-11ea-8b95-9afb6bbb16c5.png) | ![image](https://user-images.githubusercontent.com/8419308/78920258-5af1f480-7a50-11ea-89f1-e98012f01b6a.png) | ![image](https://user-images.githubusercontent.com/8419308/77202474-0e03a980-6ab4-11ea-865c-62393b24b59f.png) | 
|  ![image](https://user-images.githubusercontent.com/8419308/77202998-07c1fd00-6ab5-11ea-8d55-1d0e9e5f3bd0.png) | ![image](https://user-images.githubusercontent.com/8419308/78920422-9b517280-7a50-11ea-8a31-ea922f5d987d.png)  | ![image](https://user-images.githubusercontent.com/8419308/77202967-f5e05a00-6ab4-11ea-9035-a37a8de334d8.png) | 
| ![image](https://user-images.githubusercontent.com/8419308/77203863-1dd0bd00-6ab7-11ea-9e61-d135681176f6.png) | ![image](https://user-images.githubusercontent.com/8419308/78920584-de134a80-7a50-11ea-98ac-97d305b0b410.png)  | ![image](https://user-images.githubusercontent.com/8419308/77203833-0d204700-6ab7-11ea-9815-a95c6de31d5a.png) | 
| ![image](https://user-images.githubusercontent.com/8419308/77204059-8cae1600-6ab7-11ea-83cf-cd64f79caef6.png) | ![image](https://user-images.githubusercontent.com/8419308/78920726-1581f700-7a51-11ea-9e31-7e07e91040a4.png) | ![image](https://user-images.githubusercontent.com/8419308/77204023-786a1900-6ab7-11ea-90d3-bccbf48a8fc9.png) | 
| ![image](https://user-images.githubusercontent.com/8419308/77204778-16121800-6ab9-11ea-8c27-8781e0158e08.png) | ![image](https://user-images.githubusercontent.com/8419308/78921023-84f7e680-7a51-11ea-89eb-45b7075cd8f1.png) | ![image](https://user-images.githubusercontent.com/8419308/77204557-984e0c80-6ab8-11ea-9042-2ae775f1d385.png) | 
| ![image](https://user-images.githubusercontent.com/8419308/77205458-840b0f00-6aba-11ea-83cb-dc1b9a80244d.png) | ![image](https://user-images.githubusercontent.com/8419308/78921276-e5872380-7a51-11ea-99e5-4aaf180ec4d8.png) | ![image](https://user-images.githubusercontent.com/8419308/77205393-6342b980-6aba-11ea-939d-013776d6c9d5.png) | 
| ![image](https://user-images.githubusercontent.com/8419308/77205963-99346d80-6abb-11ea-8d36-e99714d07da9.png) | ![image](https://user-images.githubusercontent.com/8419308/78928701-516f8900-7a5e-11ea-94f2-8310dc59afc6.png) | ![image](https://user-images.githubusercontent.com/8419308/77205929-86219d80-6abb-11ea-807a-f2a378a3c043.png) | 
|  ![image](https://user-images.githubusercontent.com/8419308/77206424-8c644980-6abc-11ea-93f5-6e9536f1e918.png) | ![image](https://user-images.githubusercontent.com/8419308/78928624-2a18bc00-7a5e-11ea-9b31-8e68d48f8dd8.png) | ![image](https://user-images.githubusercontent.com/8419308/77206411-840c0e80-6abc-11ea-921e-42bfeabf5b04.png) | 
| ![image](https://user-images.githubusercontent.com/8419308/77206736-4bb90000-6abd-11ea-8932-eeb6f2079d34.png) |![image](https://user-images.githubusercontent.com/8419308/78921081-9a6d1080-7a51-11ea-9aa9-da16e6f3315d.png) | ![image](https://user-images.githubusercontent.com/8419308/77206719-40fe6b00-6abd-11ea-9f90-da13132f0cd3.png) |

**Comment by arouinfar** [comment]
Reviewed in 4/9/20 design meeting with @ariel-phet @kathy-phet @amanda-phet and @chrisklus, and we've decided that 0.45 is a happy medium. We would like to move forward with updating `SunConstants.DISABLED_PROPERTY`  to 0.45, and well as updating the various hard-coded opacities mentioned by @pixelzoom. Assigning to @chrisklus.

**Comment by terracoda** [comment]
In some cases, using opacity doesn't seem appropriate because, the background begins to show through the control (see the slider on the battery and the Pause/Play controls on the grid). 

I don't know much about color, but would a combination of opacity and desaturation be a good option as mentioned in item 4 of this web page on [designing button states](https://cloudfour.com/thinks/designing-button-states/). 

Also, it is never a good idea to use color alone to convey something meaningful. Do 

I am wondering if their is other cuing that could be used to communicate the disabled state of controls in addition to the color change. For example, some form control designs use a disabled icon coupled with a greyish/lighter colors of a disabled control.  And in some cases a bit of animation in addition to an icon and a color change.

See item 5 in [designing button states](https://cloudfour.com/thinks/designing-button-states/) the animated hover or active states for a button.

**Comment by kathy-phet** [comment]
@terracoda - This issues has primarily come up because in PhET-iO the ability to disable something is present for clients. In this case, you often want to be able to read what is available, so going too dim is undesirable. We use disable sparcely in our basic version of the simulations. As we come across those cases in our regular simulations, we can explore if some of these other strategies. would be good additions. Usually a disabled component is not really that central pedagogically. 

With the recommendation we came to above, it seems like it is consistent with Option 4 version 1 in the link you provided (which does have the green check). We don't tend to have situations like the undesirable Option 4 version 2.

**Comment by terracoda** [comment]
@kathy-phet thanks for the clarification that this is not a system wide solution for PhET sims in general.

**Comment by chrisklus** [comment]
I updated SunConstants.DISABLED_OPACITY to 0.45 in the above commit. I searched for `= 0.3`, `: 0.3`, and `? 0.3` project wide, and `0.3` in `sun` and `scenery-phet`. I found one sim-specific usage of 0.3 that seemed like it should be using `SunConstants.DisabledOpacity` - reviewer do you agree, or should we not touch sim code and revert that change? I also updated a usage in MoveToTrashButton.js and tested in Pendulum Lab.

Randomly selected @pixelzoom from the list of developers involved in this issue to review.

**Comment by pixelzoom** [comment]
Looks good @chrisklus.  `MoveToTrashButton` has some other problems related to opacity, but we'll track that in https://github.com/phetsims/scenery-phet/issues/598.  

Closing.
