### ISSUE TITLE
Review phet-io structure of EnabledComponent

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#586]
From over in https://github.com/phetsims/sun/issues/257 @jbphet said:

>There are some lines of code that were related to phet-io. I looked at these, but I'm afraid I lack the expertise in this specific area to be able to comment constructively, and I would recommend having someone with more knowledge of phet-io internals review them.

@samreid can you take a look at `EnabledComponet` in a phet-io context. Any thoughts or possible ways to improve it?

**Comment by samreid** [comment]
I tested pH scale with its `phScale.microScreen.view.graphNode.graphControlPanel.graphUnitsSwitch`, and I tried as-is and commenting out the call to `this.initializeEnabledComponent( options );`.  Studio correctly showed the `enabledProperty` when this was initialized.  I didn't have any phet-io specific recommendations (though there is one question below).  My other questions and comments are more general.

- [ ] should `assertMutuallyExclusiveOptions` be used?
- [ ] revise the header documentation to be less general
- [ ] use arrow function for dispose?
- [ ] we don't need `removeLinkedElement`, right?
- [ ] Did you consider only self-linking for Node, like so?

<details>

```diff
Index: js/EnabledComponent.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/EnabledComponent.js	(revision 9a3bcfa92fc0f2dd67e71697c9d35f04abf4cd32)
+++ js/EnabledComponent.js	(date 1585264049275)
@@ -11,9 +11,9 @@
 import merge from '../../phet-core/js/merge.js';
 import Node from '../../scenery/js/nodes/Node.js';
 import PhetioObject from '../../tandem/js/PhetioObject.js';
+import Tandem from '../../tandem/js/Tandem.js';
 import sun from './sun.js';
 import SunConstants from './SunConstants.js';
-import Tandem from '../../tandem/js/Tandem.js';
 
 // constants
 // TODO: maybe provide a default value for a custom made enabledProperty like in AquaRadioButton `enabled`?
@@ -81,25 +81,28 @@
           phetioFeatured: true
         }, options.enabledPropertyOptions ) );
 
-        const cursor = mixedIntoNode ? this.cursor : null;
-        const enabledListener = enabled => {
+        let disposeForNode = null;
 
-          // handle Node specific logic only if this instance is a Node.
-          if ( mixedIntoNode ) {
+        // handle Node specific logic only if this instance is a Node.
+        if ( mixedIntoNode ) {
+          const cursor = this.cursor;
+          const enabledListener = enabled => {
+
             this.interruptSubtreeInput();
             this.pickable = enabled;
             this.opacity = enabled ? 1.0 : options.disabledOpacity;
 
             // handle cursor by supporting setting back to what the cursor was when component was made disabled.
             this.cursor = enabled ? cursor : 'default';
-          }
-        };
-        this.enabledProperty.link( enabledListener );
+          };
+          this.enabledProperty.link( enabledListener );
+          disposeForNode = () => this.enabledProperty.unlink( enabledListener );
+        }
 
         // @private called by dispose
         this._disposeEnabledComponent = function() {
-          this.enabledProperty.unlink( enabledListener );
           ownsEnabledProperty && this.enabledProperty.dispose();
+          disposeForNode && disposeForNode();
         };
       },
 
```

</details>

I also considered a more duck-type-ish solution like:

```js
      initializeEnabledComponent: function( options ) {

        // options
        // create enabledProperty if necessary
        // etc.

        this.acceptEnabledComponent && this.acceptEnabledComponent();
      },
```

So that `Node` and `PhetioObject` can implement their own `acceptEnabledComponent` implementations.  This idea isn't fully baked but I thought I'd run it past you instead of/before prototyping it out.

**Comment by zepumph** [comment]
I'm going to merge this issue into the main review, for clarity, and one thread. Closing.
