### ISSUE TITLE
duplicate implementations of CloseButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#613]
While looking at https://github.com/phetsims/sun/issues/610, I discovered duplicated code in joist.Dialog.CloseButton and scenery-phet.CloseButton.  They are almost identical, and Dialog should be using scenery-phet.CloseButton.

Assigning to @ariel-phet to prioritize and assign.

**Comment by ariel-phet** [comment]
Hey @jessegreenberg since you are in Dialogs at the moment, could you go ahead and make this improvement?

**Comment by jessegreenberg** [comment]
Sounds good, looks like they are almost entirely duplicated. In order to use scenery-phet/CloseButton in Dialog we need to 
- Make the baseColor optional
- It looks like the X of the scenery-phet/CloseButton is twice as large as the value of options.iconLength, that should be fixed.
- Add options for the "X" Path, or make them consistent between the what is currently Dialog's CloseButton and scenery-phet/CloseButton.

**Comment by jessegreenberg** [comment]
Done in the above commits, @ariel-phet can you please assign a reviewer?

**Comment by ariel-phet** [comment]
I am guessing @pixelzoom can review this fairly quickly since he is familiar with the issue (but not a rush).

**Comment by pixelzoom** [comment]
Everything looks great.  I made 3 additional changes:

1. Grouped all supertype options together. It makes it easier to see what's specific to the subtype vs supertype.
2. Converted to class, since there are no occurrences of "inherit( CloseButton".
3. Added @jessegreenberg as an `@author`.

@jessegreenberg have a peek if you'd like, then feel free to close.
