### ISSUE TITLE
AccordionBox has no `reset()` function

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#614]
I think I would rather have a `reset` function than reach in and reset the `expandedProperty` manually.

**Comment by zepumph** [comment]
@Denz1994 how does the above commit look to you? I noticed that AccordionBox doesn't always own the expandedProperty, but I wondered if this was still ok for AccordionBox to reset it.

**Comment by pixelzoom** [comment]
I'll take over this one.

**Comment by pixelzoom** [comment]
@zepumph I think `expandedProperty` should be reset only if it was created by AccordionBox, for the same reason that it would be disposed only if created by AccordionBox.   And that brings up another point -- AccordionBox `dispose` is not cleaning up the `expandedProperty` that it creates -- worthy of a new issue or address here?

**Comment by zepumph** [comment]
Here seems good to me.

**Comment by pixelzoom** [comment]
The first commit above addresses `reset`.  `expandedProperty` is reset only if we own it. 

The second commit above addresses `dispose`.  `expandedProperty` was indeed being cleaned up properly.  I did not recognize the unusual dispose pattern being used here (and Emitter instead of `disposeAccordionBox`).   No changes were needed, but I added documentation for `disposeEmitterAccordionBox`.

I don't know what motivated creation of this issue, so I'm not sure if there's a sim that's relying on the previous behavior of `reset`.  So I'm labeling as "blocks publication" to be on the safe side.  So @zepumph please review with high priority.

**Comment by zepumph** [comment]
This issue was likely caused by my usage over in MyChallengeAccordionBox, which uses the default AccordionBox expandedProperty, so I think your change won't break anything there.

I searched for `accordionbox.reset` case insensitive and found GAS_PROPERTIES/SpeedAccordionBox  and KineticEnergyAccordionBox passing in an expandedProperty, no other accordionboxes being reset passed in their own expandedProperty. Most likely the above commit just simplified the code such that these GP Properties were being reset once instead of twice. If these two usages look good to you @pixelzoom, the feel free to close. Thanks for taking the lead on this.

**Comment by pixelzoom** [comment]
All looks well in gas-properties.  Closing.
