### ISSUE TITLE
produceSoundEmitter should be disposed

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#635]
Over in https://github.com/phetsims/sun/issues/631 I noticed that subtypes of ButtonModel remove individual listeners from `this.buttonModel.produceSoundEmitter`, but it is never disposed. This seemed weird to me.

I feel like it would be easier to just have the ButtonModel dispose the Emitter that it owns once.

**Comment by zepumph** [comment]
In each case in the above commit, we were unlinking from something that was disposed on the very next line.

@jbphet please review this cleanup. What do you think?

**Comment by zepumph** [comment]
In addition to the above commit, please see https://github.com/phetsims/sun/issues/636 and review https://github.com/phetsims/sun/commit/ca56f1721a4ee800a328c6001f1904698221d3f8 in concert with this issue.

I personally like this direction, as it makes the most sense to me to dispose everything in `ButtonModel.dispose`.

**Comment by jbphet** [comment]
@pixelzoom - since you're working on the button hierarchy, and I recall you and I discussing how the `produceSoundEmitter` should be disposed, I thought I'd assign this to you.

**Comment by pixelzoom** [comment]
ButtonModel created `produceSoundEmitter`, so ButtonModel should dispose it.   So that part of @zepumph's changes in 87e0d36 move things in the correct direction.  But I have problems with the rest of this change.

@zepumph said:
> Over in #631 I noticed that subtypes of ButtonModel remove individual listeners from this.buttonModel.produceSoundEmitter, but it is never disposed. This seemed weird to me.

There are no subtypes of ButtonModel involved here. These are all things that use ButtonModel via composition.

@zepumph said:
> In each case in the above commit, we were unlinking from something that was disposed on the very next line.

That is not the case. The very next line disposes of buttonModel, and you're assuming that it creates and disposes of produceSoundEmitter.  If the ever changes (for example, produceSoundEmitter is passed in to ButtonModel), then you have created a large number of memory leaks. 

f you add a listener to something that you don't own, you should remove that listener in dispose.  Period. You should not make assumptions about who own the something, and whether the owner is going to dispose of it or keep it around.  

All of the `buttonModel.produceSoundEmitter.removeListener` calls that were removed in 87e0d36 should be restored. Back to @zepumph.

**Comment by zepumph** [comment]
Makes sense to me. I understand that though it was safe in its current state, it was not the right decision nor maintainable. Closing
