### ISSUE TITLE
how to verify that a mixin is not overwriting properties

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#638]
Related to #257...

In EnabledComponent, `mixInto` checks for properties that we don't want to overwrite like this:

```js
  mixInto: function( type ) {
    const proto = type.prototype;

    assert && assert( !proto.hasOwnProperty( 'setEnabled' ), 'do not want to overwrite setEnabled' );
    assert && assert( !proto.hasOwnProperty( 'getEnabled' ), 'do not want to overwrite getEnabled' );
    assert && assert( !proto.hasOwnProperty( 'enabled' ), 'do not want to overwrite enabled' );
```

Two things to address here:

(1) `hasOwnProperty` does not detect inherited properties

(2) There's a lot of boilerplate in these assertions.

@zepumph and I discussed this, and we think that something like assertHasProperties.js is what we need here, with the assertion expression inverted.   So something like (untested):

```js
const assertNotHasProperties = function( object, properties ) {
  if ( assert && object ) {
    properties.forEach( property => {
      assert && assert( !Object.getOwnPropertyDescriptor( object, property ) &&
                        !_.some( inheritance( object.constructor ).map( type => Object.getOwnPropertyDescriptor( type.prototype, property ) ) ),
        `property not defined: ${property}` );
    } );
  }
};
```

@zepumph also suggested adding a flag to assertHasProperties.js  that inverts the logic.

@jonathanolson as the author of assertHasProperties.js, what do you recommend?

**Comment by zepumph** [comment]
>@jonathanolson as the author of assertHasProperties.js, what do you recommend??

To be clear I wrote that file (I don't want leave room for @jonathanolson to be blamed for my shoddiness), but I think that @jonathanolson will have an important perspective to provide about how best to support this for the whole prototype Hierarchy.

I was also surprised to see that this sort of pattern was not implemented in any of the mixins/traits around the project. 

Also note that this likely could be a duplicate of https://github.com/phetsims/phet-core/issues/29.

**Comment by zepumph** [comment]
Though this is still a problem generally, we have lost out only usage (that I know of) of these assertions guarding overwriting.

Perhaps the solution to this problem is with the new, es6 mixin pattern, since it involves inheritance, we can directly check on that type. For example `DensityBuoyancyModal`. @jonathanolson what do you recommend?

**Comment by jonathanolson** [comment]
I think with the new mixin pattern, it's now almost the same problem with normal inheritance. For methods, we can call `super.method && super.method()` if desired?

Would this also be valuable in normal inheritance code too? E.g. `Node` making sure things haven't been previously defined due to potential overrides? We typically have possibilities for naming conflicts there too.

**Comment by zepumph** [comment]
I understand that. Perhaps if we need to make sure that we don't override, then we can check like `assert && assert( typeof super.method !== 'function', . . . )` or something like that.

I don't know of a usage for this right now, so I'm happy closing. Over to @pixelzoom.

**Comment by pixelzoom** [comment]
I don't feel like we got anywhere with this, but I'm tired of the issue. So closing.
