### ISSUE TITLE
PhET-iO Design for NumberControl

### ISSUE THREAD

**Issue by arouinfar** [phetsims/sun#686]
Related to https://github.com/phetsims/projectile-motion/issues/244

Here's an example of what the studio tree currently looks like for a NumberControl

<img src="https://user-images.githubusercontent.com/8419308/109109786-31d36480-76f3-11eb-8f67-a7e108eb94a7.png" width=200>

Some of the decisions we made about NumberSpinner in https://github.com/phetsims/sun/issues/575 are appropriate here.
- [x] Change `leftArrowButton` to `decrementButton`
- [x] Change `rightArrowButton` to `incrementButton`
- [x] The `enabledProperty` of these buttons should be phetioReadOnly: true and phetioFeatured: false.

We'd also like to create something like ComboBox's `displayOnlyProperty`. There could be situations where a client would want to disable interaction with the NumberControl, but reducing the opacity of the title and NumberDisplay would not be desirable. 

Setting `numberControl.displayOnlyProperty` to true could hide the slider/tweakers. Here's an example of what it would look like in context for the Diameter and Gravity NumberControls:
![image](https://user-images.githubusercontent.com/8419308/109110940-4ca6d880-76f5-11eb-9e7c-fa730d379337.png)

Assigning the PhET-iO team and tagging for discussion at PhET-iO meeting.

**Comment by arouinfar** [comment]
Discussed with @kathy-phet and @zepumph during the Projectile Motion design meeting, and things looked reasonable to @zepumph. I'm untagging this for phet-io design meeting, and assigning to @zepumph.

**Comment by zepumph** [comment]
It is unlikely that I get to this before my June vacation, coassigning.

**Comment by samreid** [comment]
@zepumph would you like to take the lead on this?  Or please reassign me if I should work on it.

**Comment by zepumph** [comment]
Arrow button tweaks above, now onto the displayOnlyProperty

**Comment by zepumph** [comment]
Just like in ComboBox, I made the displayOnlyProperty read-only. Please review by testing in Projectile Motion, Density, or Gravity Force Lab in studio, where each NumberControl should now have a `displayOnlyProperty`.

**Comment by pixelzoom** [comment]
I'm sad to see that we're still using this pattern for adding the "display only" feature.  We previously decided that ComboBox was not a good pattern -- that is, hiding specific UI subcomponents to try to make something look like a display.  Instead of hiding subcomponents, we decided it was better to have a "display only" version of any UI component that needs that feature.  

@zepumph did you use this pattern here for expediency, or because you weren't aware of the previous decisions?

**Comment by pixelzoom** [comment]
It also seems like this should have gone to a developer for review, before passing off to the designer for review.

**Comment by zepumph** [comment]
>We previously decided that ComboBox was not a good pattern

Can you link that decision for this issue please. 

What would be an alternative, to create duplicate the titleNode and numberDisplay and to swap out those other components? I don't think I understand.

**Comment by zepumph** [comment]
Isn't this a design consideration? I was given a spec in https://github.com/phetsims/sun/issues/686#issue-816121070 that shows half of the components hidden. 

@pixelzoom can you please recommend a path forward.

**Comment by pixelzoom** [comment]
> Can you link that decision for this issue please.
> 
> What would be an alternative, to create duplicate the titleNode and numberDisplay and to swap out those other components? I don't think I understand.

From the March 4, 2021 PhET-iO meeting notes, https://docs.google.com/document/d/1-nqTlDtLtPB8JrdDrE8KdJB-4Phwe6QvTV_UnsZrteg/edit:

> ✓(from last week) AR: PhET-iO design patterns for NumberControl (sun/#686), AccordionBox (sun/#687) and Checkbox
AR: I really like how displayOnlyProperty looks in studio, it would be nice to have this feature elsewhere
CM: Expensive, Needs a way to test, Do we want to do this? Do we want to do this or have a “value only component” as a child of each of these components? Would this be easier implementation, testing, a11y, option. Have interactive components use that thing through composition? 

As I recall, we then had a significant discussion about this. I don't know who was taking notes, but they didn't capture any of the important points.  The points that I recall were:
* The ComboBox pattern can result in an interior UX. The case of ComboBox, we have a "display only" that looks like a push button. 
* Going forward, we should design what we wanted "display only" to look like for a UI component.
* If it's trivial to support that design by hiding subcomponent, do so.
* Otherwise implement a "display only" version of the UI component. 
* There are implementation and maintance advantages to keeping the implements of a UI component and its "display only" version separate.  We discussed whether the might even be in separate .js files.  
* NumberControl and AccordionBox were examples that we felt we need to look at closely, because they are already complicated implementations. 

I do recall that @arouinfar @kathy-phet @samreid were all involved in this conversation.

**Comment by pixelzoom** [comment]
> Isn't this a design consideration? I was given a spec in https://github.com/phetsims/sun/issues/686#issue-816121070 that shows half of the components hidden. 


What are you asking here? Are you asking why the implementation of a design spec needs to be reviewed?

**Comment by pixelzoom** [comment]
> @pixelzoom can you please recommend a path forward.

We established a path forward. My recommendation is to take it.

**Comment by pixelzoom** [comment]
> * If it's trivial to support that design by hiding subcomponent, do so.
> * Otherwise implement a "display only" version of the UI component.

For NumberControl, the issue that I see with simply hiding subcomponents is layout.  NumberControl has a flexible layout system, and we choose a layout based on how we want the title, NumberDisplay, ArrowButtons, and Slider to be arranged.  If you hide the ArrowButtons and Slider, the layout that you've chosen may no longer make sense.  So the least that you need is a way to optionally specify a different layout when the NumberControl is display-only.

**Comment by pixelzoom** [comment]
Here's a concerte example of what I'm pointing out in https://github.com/phetsims/sun/issues/686#issuecomment-899796691.  This is the Atom control panel from Rutherford Scattering:

<img width="266" alt="screenshot_1184" src="https://user-images.githubusercontent.com/3046552/129625729-8f224ed0-34fd-439e-80d9-c6bff3e74806.png">

It uses NumberControl with `layoutFuncton: createLayoutFunction3`.  With your implement of the "display only" feature, that panel looks like this when `displayOnlyProperty` is set to true:

<img width="267" alt="screenshot_1185" src="https://user-images.githubusercontent.com/3046552/129626211-7ea33298-1d7b-40e0-bd4f-0cd0341abff9.png">

Like ComboBox, this results in a wonky user-interface, certainly not what someone would design.

**Comment by zepumph** [comment]
Alright we have https://github.com/phetsims/sun/issues/714, @arouinfar, please review everything else but the `displayOnlyProperty` work.

**Comment by zepumph** [comment]
We touched base with @arouinfar this week during PhET-iO meeting to confirm that Projectile motion doesn't need this feature, and that we will thoughtfully design the feature over in https://github.com/phetsims/sun/issues/714

**Comment by zepumph** [comment]
I noticed in GFL (and perhaps others), we had used overrides to provide the above info (great, we can delete that), but also adding featured to `titleNode.visibleProperty`. Do you want to add that also generally?

**Comment by zepumph** [comment]
The 4 above have been added. Note the two strange things I ran into while working here in separate issues above. I don't have time to investigate this right now, but I will soon. 

@arouinfar please review and let me know if you want the titleNode visibleProperty to be featured.
