### ISSUE TITLE
Carousel Combo Box page control looks odd when there is only 1 page

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#689]
Related to https://github.com/phetsims/sun/issues/673 and discovered in https://github.com/phetsims/bamboo/issues/26, the page control looks odd/buggy when there is only 1 page:

![image](https://user-images.githubusercontent.com/679486/113027918-e411a800-9147-11eb-8758-0a3d7140eff4.png)

Assigning @zepumph and @pixelzoom who worked on the carousel combo box and its page control.

**Comment by pixelzoom** [comment]
Yes, I saw the "1 page" part of the description.   But you didn't say what aspect looks odd.  It sounds like you're only concerned with the page control, but I'm still not sure because you haven't commented on whether the disabled arrow buttons are significant.

If it's only the page control that bothers you....It's trivial to add the page control only if there's > 1 page.  I did just that, then discovered that sun unit tests are failing, so I can't commit.   Here's the patch, if you want to apply:

<details>
<summary>Patch</summary>

Index: js/CarouselComboBox.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/CarouselComboBox.js b/js/CarouselComboBox.js
--- a/js/CarouselComboBox.js	(revision 5d3249f76205ad722a4d8138449dd140e25716fb)
+++ b/js/CarouselComboBox.js	(date 1617133407131)
@@ -125,16 +125,23 @@
     );
     assert && assert( carouselItemNodes.length === comboBoxItems.length, 'expected a carouselItem for each comboBoxItem' );
 
+    const hBoxChildren = [];
+
     // Create the carousel.
     const carousel = new Carousel( carouselItemNodes, options.carouselOptions );
+    hBoxChildren.push( carousel );
 
     // page control
-    const pageControl = new PageControl( carousel.numberOfPages, carousel.pageNumberProperty, options.pageControlOptions );
+    let pageControl;
+    if ( carousel.numberOfPages > 1 ) {
+      pageControl = new PageControl( carousel.numberOfPages, carousel.pageNumberProperty, options.pageControlOptions );
+      hBoxChildren.push( pageControl );
+    }
 
     // Page control to the left of carousel
     const carouselAndPageControl = new HBox( {
       spacing: 4,
-      children: [ carousel, pageControl ]
+      children: hBoxChildren
     } );
 
     // Pressing this button pops the carousel up and down
@@ -171,7 +178,7 @@
         // choices from the carousel. See https://github.com/phetsims/sun/issues/677
         if ( !phet.chipper.isFuzzEnabled() || dotRandom.nextDouble() < 0.25 ) {
           const trail = event.trail;
-          if ( !trail.containsNode( button ) && !trail.containsNode( carousel ) && !trail.containsNode( pageControl ) ) {
+          if ( !trail.containsNode( button ) && !trail.containsNode( carousel ) && ( !pageControl || !trail.containsNode( pageControl ) ) ) {
             carouselAndPageControl.visible = false;
           }
         }

</details>

**Comment by samreid** [comment]
Yes, the disabled arrows didn't bother me at all.  I'll take a look at the patch.

**Comment by samreid** [comment]
I repaired the failing unit test and committed the patch, closing.
