### ISSUE TITLE
Can Dialog pass nested options to the Popupable mixin?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/sun#722]
In https://github.com/phetsims/sun/issues/719 we noticed that Dialog could not easily pass options to Popupable, which is using the new mixin pattern. Dialog is passing options to its super class (Panel), but you have to pick out the options that you want to give to Popupable in the first argument. This was a little confusing because it looked like Dialog extended Popupable
```js
class Dialog extends Popupable( Panel ) {
```

Popupable is the only mixin of this style that takes options, which is why we are noticing this issue here.

The Popupable constructor looks like
```js

    constructor( options, ...args ) {
      super( ...args );
```
@zepumph and I couldn't find a way to get a consistent `options` element from `...args` which is likely why this pattern is implemented this way.

Can we use nested options in Dialog to pass Popupable options to Popupable?
```js
super( options.popupableOptions, dialogContent, options );
```

Tagging @jonathanolson as the author of Popupable, but we are going to try this change.

**Comment by samreid** [comment]
> Popupable is the only mixin of this style that takes options, which is why we are noticing this issue here.

Using the search regex `extends .*\( .* \) \{` reveals many other occurrences which use the parametric mixin pattern:

```js
class DensityCompareModel extends BlockSetModel( DensityBuoyancyModel, BlockSet, BlockSet.SAME_MASS ) {
```

```js
class ExampleExpandingRectangle extends WidthSizable( HeightSizable( Rectangle ) ) {
```

etc.  But I agree this style is relatively new and rare.

> This was a little confusing because it looked like Dialog extended Popupable

Correct me if I misunderstand, but I think `Dialog` extends `Popupable(Panel)`. `Popupable(Panel)` creates a new (in this case, anonymous) type which is a supertype for Dialog.  As much as possible we should use our subtype patterns here

> In the above commits I made the options passed to the Popupable mixin nested under the main options so that we don't have to pick out the options that we want to pass on to Popupable. 

For our idiomatic supertype usages, we don't pluck out or nest options that go to a supertype--we pass all of them.  So it seems we should do the same thing here.  I can see there is also precedent for this in `BuoyancyIntroModel` and `HackySizableHSlider`.

> so that we don't have to pick out the options that we want to pass on to Popupable

Can you help me understand why we needed to pick out options for Popupable?  Was there some effect where options were getting applied in the supertype and subtype, and doubling up?

> @zepumph and I couldn't find a way to get a consistent options element from ...args which is likely why this pattern is implemented this way.

Since Dialog is the only place that uses Popupable, we could presumably change this to:

```js
constructor( options, ...args ) {
      super( options );
```

or if we want to be more general, we could perhaps pass through `...arguments` instead of `...args` to get all of them?  But I would see if maybe `super(options)` or even `super(options,...args)` works first.

I'm happy to continue the review after hearing back on the discussion points above, but should also note that @jonathanolson has more expertise in this area.

**Comment by zepumph** [comment]
Agreed @jonathanolson.

Honestly, it felt like much of what @samreid said in https://github.com/phetsims/sun/issues/722#issuecomment-937428194 was not inline with what I was seeing. Perhaps a sync communication is best.  It isn't that the pattern is only used once, its Popupable is the only mixin of this type in which it takes options, and the Node it mixes into also takes options, so we have to pass options to both, but it doesn't work to pass the same options.

**Comment by jessegreenberg** [comment]
This looks nice, thanks! A `config` is more clearly required. `required` is often used with a `config` but it was intended for fields of the `config` (looking at its assertion message).  Are you OK with the above commit to catch the missing `config` before we hit something like "Assertion failed: object is not compatible with merge"?
