### ISSUE TITLE
VSlider has incorrect defaults for track size and knob dimensions

### ISSUE THREAD

**Issue by samreid** [phetsims/sun#733]
Discovered in https://github.com/phetsims/bamboo/issues/50, if you create a default VSlider with default `trackSize` and `thumbSize`, the sliders look like this, but drag up and down:

![image](https://user-images.githubusercontent.com/679486/146695401-b84f3c30-145e-40aa-b976-60c1ea93bb37.png)

So perhaps VSlider should use different defaults, like this (but with factored out constants):

```js
    options = merge( {
      orientation: Orientation.VERTICAL,
      trackSize: new Dimension2( 5, 100 ),
      thumbSize: new Dimension2( 34, 17 )
    }, options );
```

Or perhaps if Slider detects `orientation: Orientation.HORIZONTAL`, it should swap widths and heights.  Assigning @pixelzoom since this issue may be related to https://github.com/phetsims/sun/issues/380

**Comment by pixelzoom** [comment]
Looks like this problem was introduced in https://github.com/phetsims/sun/commit/53706aa5fef79d0805840dbd7e4a04b3a555ef9e.  I'll check it out.

**Comment by pixelzoom** [comment]
The problem is present in usages of VSlider that do not specific trackSize and thumbSize.

These uses specify both trackSize and thumbSize, and should not be a problem (but will be tested):

- [ ] capacitor-lab-basics BatteryNode
- [ ] color-vision RGBSlider
- [ ] gravity-and-orbits ZoomControl
- [ ] greenhouse-effect ConcentrationControlPanel
- [ ] least-squares-regression MyLineControlPanel
- [ ] neuron ZoomControl
- [ ] normal-modes NormalModeSpectrumAccordionBox
- [ ] ohms-law SliderUnit
- [ ] resistance-in-a-wire SliderUnit
- [ ] scenery-phet HeaterCoolerFront

These uses do NOT specify both trackSize and thumbSize, and are expected to exhibit this problem:

- [ ] curve-fitting CoefficientSliderNode
- [ ] energy-forms-and-changes SunNode
- [ ] graphing-quadratics GQSlider
- [ ] griddle GriddleDemoScreenView
- [ ] molarity VerticalSlider
- [ ] scenery-phet ComponentsScreenView
- [ ] sun ComponentsScreenView

**Comment by pixelzoom** [comment]
Fixed in the above commits. Tested all sims listed in https://github.com/phetsims/sun/issues/733#issuecomment-1009379945, as well as a random sampling of HSliders.

Back to @samreid for review.

**Comment by samreid** [comment]
The changes seem good, thanks!  Closing.
