### ISSUE TITLE
TypeScript conversion of `*ButtonInteractionStateProperty` classes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#750]
I'm converting `*ToggleButtonInteractionStateProperty` classes to TypeScript, and encountering enough incorrect JSdoc type expressions that I'm concerned.  So I'm creating this issue to track my changes, and have @jbphet review when I'm done.

**Comment by pixelzoom** [comment]
@jbphet please review.  

The main problem I encountered is that all of the constructors indicated `@param {ButtonModel} buttonModel`. And that definitely was not the case, there were specific subclasses of ButtonModel that were needed.

**Comment by jbphet** [comment]
Changes look good.  Having the greater specificity for the model types needed in these derived types is a good improvement.  I added the direct export of the class declaration that had been done for the other files to `PushButtonInteractionStateProperty` for consistency and did some edits on the comments.

I also changed the title of this issue since, as originally written, it described a smaller set of files than were actually changed.

@pixelzoom - I'm reasonably certain that none of this would be controversial with you, so I'm going to close.  You're welcome to look it over if you see it go by.
