### ISSUE TITLE
Address uses of `any` for TButtonAppearanceStrategy and TContentAppearanceStrategy

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sun#754]
There are several uses of `any` in sun, all related to TButtonAppearanceStrategy and TContentAppearanceStrategy (types created by @zepumph).  These should be replaced with correct types. 

Occurrences of `any` in:
- [x] TButtonAppearanceStrategy
- [x] TContentAppearanceStrategy
- [x] ButtonNode.FlatAppearanceStrategy
- [x] RectangularButton.ThreeDAppearanceStrategy
- [x] RectangularButton.ContentAppearanceStrategy
- [x] RoundButton.ThreeDAppearanceStrategy

... and possibly elsewhere?

Assigning to @zepumph and @jbphet (the original author).

**Comment by jbphet** [comment]
After making the commits shown above, I closely compared the buttons to those found in published versions of the sims, and they look a little different.  I'm not sure that this is the result of my changes, because I didn't check prior to making the changes, but I could back them out and find out for sure if necessary.  But the differences are fairly subtle, and might not really matter, so I'm going to ask around a bit before spending much time on this.  Here is a before-and-after comparison for some buttons Molecules and Light:

MAL 1.5.3:

![image](https://user-images.githubusercontent.com/3082831/192883153-6b8545b7-1f2f-4084-bc8e-be6705a799c7.png)

MAL on master as of today:

![image](https://user-images.githubusercontent.com/3082831/192883001-d039e115-9721-4014-96b7-e71f969adac9.png)

These are from Chrome version 105.0.5195.127 .

The stroke on the round buttons looks a bit more pronounced, and on the rectangular button it looks a little less pronounced.

**Comment by jbphet** [comment]
I reviewed the visual changes with @arouinfar and @pixelzoom (in separate discussions), and we all agreed that they are insignificant enough that we don't need to investigate why the differences exist.  Assigning to @pixelzoom to review.

**Comment by pixelzoom** [comment]
I’m still seeing “appearance strategy” problems with zoom buttons.  They are missing stroke. For example, in Natural Selection:

<img width="132" alt="screenshot_1898" src="https://user-images.githubusercontent.com/3046552/193664534-ae19d2c1-47cd-4334-8341-4cd4fa74b6b4.png">

They should look like this:

<img width="132" alt="screenshot_1899" src="https://user-images.githubusercontent.com/3046552/193664753-0579ae5c-1bf6-4305-85b0-308a5c54a1f8.png">

**Comment by arouinfar** [comment]
The examples I reviewed with @jbphet didn't include a case where two buttons are in direct contact, like the zoom buttons  The lack of a stroke separating the zoom buttons seems problematic to me.

**Comment by jbphet** [comment]
Here is another instance from the bamboo repo demo:

![image](https://user-images.githubusercontent.com/3082831/193952524-f3ff7a0e-aaab-45f8-a172-ec6e29919ce4.png)

**Comment by jbphet** [comment]
The problem with missing strokes for Zoom buttons using the flat appearance strategy was because in the course of porting this code to TypeScript, I'd changed to code to only create a default stroke if the provided stroke was `undefined`.  The previous code created a default stroke when any falsey value, including `null`, was provided as the stroke, and some of the base classes set this value explicitly.  I have changed the code to be more like the previous code, but I acknowledge that this is a bit inconsistent with other nodes, where a `null` value for the stroke means "don't use a stroke on this node".  As with https://github.com/phetsims/sun/issues/772, I'm making a decision to go with backward compatibility over perfect consistency.

@pixelzoom - Please continue the review and let me know if you see anything in the code or the sims that look problematic.  When you're done, assign this back to me and I'll request that QA go through the sims and look for any other cases of buttons that look like they are missing strokes.

**Comment by pixelzoom** [comment]
I took a quick look through the code and commits, and I don't see anything that looks problematic.  The example in natural-selection and bamboo demo also look OK now.

Back to @jbphet in case there's anything else to do here.

**Comment by jbphet** [comment]
Thanks for the review, I think that should do it.  Closing.
